//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 08:16:12 PM EEST 
//


package tr.com.agem.arya.metadata.arya.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for chartsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chartsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{aryaportal.org}baseGroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;attGroup ref="{aryaportal.org}plotAttrGroup"/>
 *       &lt;attGroup ref="{aryaportal.org}rootAttrGroup"/>
 *       &lt;attGroup ref="{aryaportal.org}abstractComponentAttrGroup"/>
 *       &lt;attGroup ref="{aryaportal.org}mouseAttrGroup"/>
 *       &lt;attribute name="type" type="{aryaportal.org}chartsTypeAttrType" />
 *       &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subtitle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="alignTicks" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="animation" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="backgroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="borderColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="borderRadius" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="borderWidth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="chart" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="colors" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="credits" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enableZoomSelection" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="exporting" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ignoreHiddenSeries" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="inverted" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="labels" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="legend" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="margin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="marginBottom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="marginLeft" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="marginRight" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="marginTop" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="navigation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="options" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pinchType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="plotBackgroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="plotBackgroundImage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="plotBorderColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="plotBorderWidth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="plotOptions" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="plotShadow" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="polar" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="reflow" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="selectionMarkerFill" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shadow" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="showAxes" type="{aryaportal.org}booleanType" />
 *       &lt;attribute name="spacing" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spacingBottom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spacingLeft" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spacingRight" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spacingTop" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="style" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="theme" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tooltip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="zclass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="zoomType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="onSelection" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chartsType", propOrder = {
    "baseGroup"
})
public class ChartsType {

    @XmlElementRefs({
        @XmlElementRef(name = "arya", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "custom-attributes", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "attribute", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "template", namespace = "aryaportal.org", type = JAXBElement.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> baseGroup;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "model")
    protected String model;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "subtitle")
    protected String subtitle;
    @XmlAttribute(name = "width")
    protected String width;
    @XmlAttribute(name = "height")
    protected String height;
    @XmlAttribute(name = "alignTicks")
    protected String alignTicks;
    @XmlAttribute(name = "animation")
    protected String animation;
    @XmlAttribute(name = "backgroundColor")
    protected String backgroundColor;
    @XmlAttribute(name = "borderColor")
    protected String borderColor;
    @XmlAttribute(name = "borderRadius")
    protected String borderRadius;
    @XmlAttribute(name = "borderWidth")
    protected String borderWidth;
    @XmlAttribute(name = "chart")
    protected String chart;
    @XmlAttribute(name = "colors")
    protected String colors;
    @XmlAttribute(name = "credits")
    protected String credits;
    @XmlAttribute(name = "enableZoomSelection")
    protected String enableZoomSelection;
    @XmlAttribute(name = "exporting")
    protected String exporting;
    @XmlAttribute(name = "ignoreHiddenSeries")
    protected String ignoreHiddenSeries;
    @XmlAttribute(name = "inverted")
    protected String inverted;
    @XmlAttribute(name = "labels")
    protected String labels;
    @XmlAttribute(name = "legend")
    protected String legend;
    @XmlAttribute(name = "margin")
    protected String margin;
    @XmlAttribute(name = "marginBottom")
    protected String marginBottom;
    @XmlAttribute(name = "marginLeft")
    protected String marginLeft;
    @XmlAttribute(name = "marginRight")
    protected String marginRight;
    @XmlAttribute(name = "marginTop")
    protected String marginTop;
    @XmlAttribute(name = "navigation")
    protected String navigation;
    @XmlAttribute(name = "options")
    protected String options;
    @XmlAttribute(name = "pinchType")
    protected String pinchType;
    @XmlAttribute(name = "plotBackgroundColor")
    protected String plotBackgroundColor;
    @XmlAttribute(name = "plotBackgroundImage")
    protected String plotBackgroundImage;
    @XmlAttribute(name = "plotBorderColor")
    protected String plotBorderColor;
    @XmlAttribute(name = "plotBorderWidth")
    protected String plotBorderWidth;
    @XmlAttribute(name = "plotOptions")
    protected String plotOptions;
    @XmlAttribute(name = "plotShadow")
    protected String plotShadow;
    @XmlAttribute(name = "polar")
    protected String polar;
    @XmlAttribute(name = "reflow")
    protected String reflow;
    @XmlAttribute(name = "selectionMarkerFill")
    protected String selectionMarkerFill;
    @XmlAttribute(name = "shadow")
    protected String shadow;
    @XmlAttribute(name = "showAxes")
    protected String showAxes;
    @XmlAttribute(name = "spacing")
    protected String spacing;
    @XmlAttribute(name = "spacingBottom")
    protected String spacingBottom;
    @XmlAttribute(name = "spacingLeft")
    protected String spacingLeft;
    @XmlAttribute(name = "spacingRight")
    protected String spacingRight;
    @XmlAttribute(name = "spacingTop")
    protected String spacingTop;
    @XmlAttribute(name = "style")
    protected String style;
    @XmlAttribute(name = "theme")
    protected String theme;
    @XmlAttribute(name = "tooltip")
    protected String tooltip;
    @XmlAttribute(name = "zclass")
    protected String zclass;
    @XmlAttribute(name = "zoomType")
    protected String zoomType;
    @XmlAttribute(name = "onSelection")
    protected String onSelection;
    @XmlAttribute(name = "onPlotClick")
    protected String onPlotClick;
    @XmlAttribute(name = "onPlotCheckboxClick")
    protected String onPlotCheckboxClick;
    @XmlAttribute(name = "onPlotDrillDown")
    protected String onPlotDrillDown;
    @XmlAttribute(name = "onPlotDrillUp")
    protected String onPlotDrillUp;
    @XmlAttribute(name = "onPlotHide")
    protected String onPlotHide;
    @XmlAttribute(name = "onPlotLegendItemClick")
    protected String onPlotLegendItemClick;
    @XmlAttribute(name = "onPlotMouseOut")
    protected String onPlotMouseOut;
    @XmlAttribute(name = "onPlotMouseOver")
    protected String onPlotMouseOver;
    @XmlAttribute(name = "onPlotShow")
    protected String onPlotShow;
    @XmlAttribute(name = "onBookmarkChange")
    protected String onBookmarkChange;
    @XmlAttribute(name = "onClientInfo")
    protected String onClientInfo;
    @XmlAttribute(name = "apply")
    protected String apply;
    @XmlAttribute(name = "auService")
    protected String auService;
    @XmlAttribute(name = "autag")
    protected String autag;
    @XmlAttribute(name = "binder")
    protected String binder;
    @XmlAttribute(name = "children")
    protected String children;
    @XmlAttribute(name = "form")
    protected String form;
    @XmlAttribute(name = "forward")
    protected String forward;
    @XmlAttribute(name = "fulfill")
    protected String fulfill;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "mold")
    protected String mold;
    @XmlAttribute(name = "onFulfill")
    protected String onFulfill;
    @XmlAttribute(name = "stubonly")
    protected String stubonly;
    @XmlAttribute(name = "use")
    protected String use;
    @XmlAttribute(name = "viewModel")
    protected String viewModel;
    @XmlAttribute(name = "visible")
    protected String visible;
    @XmlAttribute(name = "forEach")
    protected String forEach;
    @XmlAttribute(name = "forEachBegin")
    protected String forEachBegin;
    @XmlAttribute(name = "forEachEnd")
    protected String forEachEnd;
    @XmlAttribute(name = "if")
    protected String _if;
    @XmlAttribute(name = "self")
    protected String self;
    @XmlAttribute(name = "unless")
    protected String unless;
    @XmlAttribute(name = "onClick")
    @XmlSchemaType(name = "anySimpleType")
    protected String onClick;
    @XmlAttribute(name = "onRightClick")
    @XmlSchemaType(name = "anySimpleType")
    protected String onRightClick;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the baseGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * {@link JAXBElement }{@code <}{@link AryaType }{@code >}
     * {@link JAXBElement }{@code <}{@link AttributeType }{@code >}
     * {@link JAXBElement }{@code <}{@link TemplateType }{@code >}
     * {@link JAXBElement }{@code <}{@link CustomAttributesType }{@code >}
     * 
     * 
     */
    public List<Object> getBaseGroup() {
        if (baseGroup == null) {
            baseGroup = new ArrayList<Object>();
        }
        return this.baseGroup;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the subtitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * Sets the value of the subtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtitle(String value) {
        this.subtitle = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the alignTicks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlignTicks() {
        return alignTicks;
    }

    /**
     * Sets the value of the alignTicks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlignTicks(String value) {
        this.alignTicks = value;
    }

    /**
     * Gets the value of the animation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnimation() {
        return animation;
    }

    /**
     * Sets the value of the animation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnimation(String value) {
        this.animation = value;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor(String value) {
        this.backgroundColor = value;
    }

    /**
     * Gets the value of the borderColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderColor() {
        return borderColor;
    }

    /**
     * Sets the value of the borderColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderColor(String value) {
        this.borderColor = value;
    }

    /**
     * Gets the value of the borderRadius property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderRadius() {
        return borderRadius;
    }

    /**
     * Sets the value of the borderRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderRadius(String value) {
        this.borderRadius = value;
    }

    /**
     * Gets the value of the borderWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderWidth() {
        return borderWidth;
    }

    /**
     * Sets the value of the borderWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderWidth(String value) {
        this.borderWidth = value;
    }

    /**
     * Gets the value of the chart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChart() {
        return chart;
    }

    /**
     * Sets the value of the chart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChart(String value) {
        this.chart = value;
    }

    /**
     * Gets the value of the colors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColors() {
        return colors;
    }

    /**
     * Sets the value of the colors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColors(String value) {
        this.colors = value;
    }

    /**
     * Gets the value of the credits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredits() {
        return credits;
    }

    /**
     * Sets the value of the credits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredits(String value) {
        this.credits = value;
    }

    /**
     * Gets the value of the enableZoomSelection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnableZoomSelection() {
        return enableZoomSelection;
    }

    /**
     * Sets the value of the enableZoomSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnableZoomSelection(String value) {
        this.enableZoomSelection = value;
    }

    /**
     * Gets the value of the exporting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporting() {
        return exporting;
    }

    /**
     * Sets the value of the exporting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporting(String value) {
        this.exporting = value;
    }

    /**
     * Gets the value of the ignoreHiddenSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIgnoreHiddenSeries() {
        return ignoreHiddenSeries;
    }

    /**
     * Sets the value of the ignoreHiddenSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIgnoreHiddenSeries(String value) {
        this.ignoreHiddenSeries = value;
    }

    /**
     * Gets the value of the inverted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInverted() {
        return inverted;
    }

    /**
     * Sets the value of the inverted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInverted(String value) {
        this.inverted = value;
    }

    /**
     * Gets the value of the labels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabels() {
        return labels;
    }

    /**
     * Sets the value of the labels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabels(String value) {
        this.labels = value;
    }

    /**
     * Gets the value of the legend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegend() {
        return legend;
    }

    /**
     * Sets the value of the legend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegend(String value) {
        this.legend = value;
    }

    /**
     * Gets the value of the margin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMargin() {
        return margin;
    }

    /**
     * Sets the value of the margin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMargin(String value) {
        this.margin = value;
    }

    /**
     * Gets the value of the marginBottom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarginBottom() {
        return marginBottom;
    }

    /**
     * Sets the value of the marginBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarginBottom(String value) {
        this.marginBottom = value;
    }

    /**
     * Gets the value of the marginLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarginLeft() {
        return marginLeft;
    }

    /**
     * Sets the value of the marginLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarginLeft(String value) {
        this.marginLeft = value;
    }

    /**
     * Gets the value of the marginRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarginRight() {
        return marginRight;
    }

    /**
     * Sets the value of the marginRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarginRight(String value) {
        this.marginRight = value;
    }

    /**
     * Gets the value of the marginTop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarginTop() {
        return marginTop;
    }

    /**
     * Sets the value of the marginTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarginTop(String value) {
        this.marginTop = value;
    }

    /**
     * Gets the value of the navigation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavigation() {
        return navigation;
    }

    /**
     * Sets the value of the navigation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavigation(String value) {
        this.navigation = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptions(String value) {
        this.options = value;
    }

    /**
     * Gets the value of the pinchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinchType() {
        return pinchType;
    }

    /**
     * Sets the value of the pinchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinchType(String value) {
        this.pinchType = value;
    }

    /**
     * Gets the value of the plotBackgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlotBackgroundColor() {
        return plotBackgroundColor;
    }

    /**
     * Sets the value of the plotBackgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlotBackgroundColor(String value) {
        this.plotBackgroundColor = value;
    }

    /**
     * Gets the value of the plotBackgroundImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlotBackgroundImage() {
        return plotBackgroundImage;
    }

    /**
     * Sets the value of the plotBackgroundImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlotBackgroundImage(String value) {
        this.plotBackgroundImage = value;
    }

    /**
     * Gets the value of the plotBorderColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlotBorderColor() {
        return plotBorderColor;
    }

    /**
     * Sets the value of the plotBorderColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlotBorderColor(String value) {
        this.plotBorderColor = value;
    }

    /**
     * Gets the value of the plotBorderWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlotBorderWidth() {
        return plotBorderWidth;
    }

    /**
     * Sets the value of the plotBorderWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlotBorderWidth(String value) {
        this.plotBorderWidth = value;
    }

    /**
     * Gets the value of the plotOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlotOptions() {
        return plotOptions;
    }

    /**
     * Sets the value of the plotOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlotOptions(String value) {
        this.plotOptions = value;
    }

    /**
     * Gets the value of the plotShadow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlotShadow() {
        return plotShadow;
    }

    /**
     * Sets the value of the plotShadow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlotShadow(String value) {
        this.plotShadow = value;
    }

    /**
     * Gets the value of the polar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolar() {
        return polar;
    }

    /**
     * Sets the value of the polar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolar(String value) {
        this.polar = value;
    }

    /**
     * Gets the value of the reflow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReflow() {
        return reflow;
    }

    /**
     * Sets the value of the reflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReflow(String value) {
        this.reflow = value;
    }

    /**
     * Gets the value of the selectionMarkerFill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectionMarkerFill() {
        return selectionMarkerFill;
    }

    /**
     * Sets the value of the selectionMarkerFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectionMarkerFill(String value) {
        this.selectionMarkerFill = value;
    }

    /**
     * Gets the value of the shadow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadow() {
        return shadow;
    }

    /**
     * Sets the value of the shadow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadow(String value) {
        this.shadow = value;
    }

    /**
     * Gets the value of the showAxes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAxes() {
        return showAxes;
    }

    /**
     * Sets the value of the showAxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAxes(String value) {
        this.showAxes = value;
    }

    /**
     * Gets the value of the spacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpacing() {
        return spacing;
    }

    /**
     * Sets the value of the spacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpacing(String value) {
        this.spacing = value;
    }

    /**
     * Gets the value of the spacingBottom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpacingBottom() {
        return spacingBottom;
    }

    /**
     * Sets the value of the spacingBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpacingBottom(String value) {
        this.spacingBottom = value;
    }

    /**
     * Gets the value of the spacingLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpacingLeft() {
        return spacingLeft;
    }

    /**
     * Sets the value of the spacingLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpacingLeft(String value) {
        this.spacingLeft = value;
    }

    /**
     * Gets the value of the spacingRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpacingRight() {
        return spacingRight;
    }

    /**
     * Sets the value of the spacingRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpacingRight(String value) {
        this.spacingRight = value;
    }

    /**
     * Gets the value of the spacingTop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpacingTop() {
        return spacingTop;
    }

    /**
     * Sets the value of the spacingTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpacingTop(String value) {
        this.spacingTop = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the theme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTheme() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTheme(String value) {
        this.theme = value;
    }

    /**
     * Gets the value of the tooltip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTooltip() {
        return tooltip;
    }

    /**
     * Sets the value of the tooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTooltip(String value) {
        this.tooltip = value;
    }

    /**
     * Gets the value of the zclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZclass() {
        return zclass;
    }

    /**
     * Sets the value of the zclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZclass(String value) {
        this.zclass = value;
    }

    /**
     * Gets the value of the zoomType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoomType() {
        return zoomType;
    }

    /**
     * Sets the value of the zoomType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoomType(String value) {
        this.zoomType = value;
    }

    /**
     * Gets the value of the onSelection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnSelection() {
        return onSelection;
    }

    /**
     * Sets the value of the onSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnSelection(String value) {
        this.onSelection = value;
    }

    /**
     * Gets the value of the onPlotClick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnPlotClick() {
        return onPlotClick;
    }

    /**
     * Sets the value of the onPlotClick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnPlotClick(String value) {
        this.onPlotClick = value;
    }

    /**
     * Gets the value of the onPlotCheckboxClick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnPlotCheckboxClick() {
        return onPlotCheckboxClick;
    }

    /**
     * Sets the value of the onPlotCheckboxClick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnPlotCheckboxClick(String value) {
        this.onPlotCheckboxClick = value;
    }

    /**
     * Gets the value of the onPlotDrillDown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnPlotDrillDown() {
        return onPlotDrillDown;
    }

    /**
     * Sets the value of the onPlotDrillDown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnPlotDrillDown(String value) {
        this.onPlotDrillDown = value;
    }

    /**
     * Gets the value of the onPlotDrillUp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnPlotDrillUp() {
        return onPlotDrillUp;
    }

    /**
     * Sets the value of the onPlotDrillUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnPlotDrillUp(String value) {
        this.onPlotDrillUp = value;
    }

    /**
     * Gets the value of the onPlotHide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnPlotHide() {
        return onPlotHide;
    }

    /**
     * Sets the value of the onPlotHide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnPlotHide(String value) {
        this.onPlotHide = value;
    }

    /**
     * Gets the value of the onPlotLegendItemClick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnPlotLegendItemClick() {
        return onPlotLegendItemClick;
    }

    /**
     * Sets the value of the onPlotLegendItemClick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnPlotLegendItemClick(String value) {
        this.onPlotLegendItemClick = value;
    }

    /**
     * Gets the value of the onPlotMouseOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnPlotMouseOut() {
        return onPlotMouseOut;
    }

    /**
     * Sets the value of the onPlotMouseOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnPlotMouseOut(String value) {
        this.onPlotMouseOut = value;
    }

    /**
     * Gets the value of the onPlotMouseOver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnPlotMouseOver() {
        return onPlotMouseOver;
    }

    /**
     * Sets the value of the onPlotMouseOver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnPlotMouseOver(String value) {
        this.onPlotMouseOver = value;
    }

    /**
     * Gets the value of the onPlotShow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnPlotShow() {
        return onPlotShow;
    }

    /**
     * Sets the value of the onPlotShow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnPlotShow(String value) {
        this.onPlotShow = value;
    }

    /**
     * Gets the value of the onBookmarkChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnBookmarkChange() {
        return onBookmarkChange;
    }

    /**
     * Sets the value of the onBookmarkChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnBookmarkChange(String value) {
        this.onBookmarkChange = value;
    }

    /**
     * Gets the value of the onClientInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnClientInfo() {
        return onClientInfo;
    }

    /**
     * Sets the value of the onClientInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnClientInfo(String value) {
        this.onClientInfo = value;
    }

    /**
     * Gets the value of the apply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApply() {
        return apply;
    }

    /**
     * Sets the value of the apply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApply(String value) {
        this.apply = value;
    }

    /**
     * Gets the value of the auService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuService() {
        return auService;
    }

    /**
     * Sets the value of the auService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuService(String value) {
        this.auService = value;
    }

    /**
     * Gets the value of the autag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutag() {
        return autag;
    }

    /**
     * Sets the value of the autag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutag(String value) {
        this.autag = value;
    }

    /**
     * Gets the value of the binder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinder() {
        return binder;
    }

    /**
     * Sets the value of the binder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinder(String value) {
        this.binder = value;
    }

    /**
     * Gets the value of the children property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildren(String value) {
        this.children = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForm(String value) {
        this.form = value;
    }

    /**
     * Gets the value of the forward property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForward() {
        return forward;
    }

    /**
     * Sets the value of the forward property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForward(String value) {
        this.forward = value;
    }

    /**
     * Gets the value of the fulfill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfill() {
        return fulfill;
    }

    /**
     * Sets the value of the fulfill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfill(String value) {
        this.fulfill = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the mold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMold() {
        return mold;
    }

    /**
     * Sets the value of the mold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMold(String value) {
        this.mold = value;
    }

    /**
     * Gets the value of the onFulfill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnFulfill() {
        return onFulfill;
    }

    /**
     * Sets the value of the onFulfill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnFulfill(String value) {
        this.onFulfill = value;
    }

    /**
     * Gets the value of the stubonly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStubonly() {
        return stubonly;
    }

    /**
     * Sets the value of the stubonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStubonly(String value) {
        this.stubonly = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUse() {
        return use;
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUse(String value) {
        this.use = value;
    }

    /**
     * Gets the value of the viewModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewModel() {
        return viewModel;
    }

    /**
     * Sets the value of the viewModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewModel(String value) {
        this.viewModel = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the forEach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForEach() {
        return forEach;
    }

    /**
     * Sets the value of the forEach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForEach(String value) {
        this.forEach = value;
    }

    /**
     * Gets the value of the forEachBegin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForEachBegin() {
        return forEachBegin;
    }

    /**
     * Sets the value of the forEachBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForEachBegin(String value) {
        this.forEachBegin = value;
    }

    /**
     * Gets the value of the forEachEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForEachEnd() {
        return forEachEnd;
    }

    /**
     * Sets the value of the forEachEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForEachEnd(String value) {
        this.forEachEnd = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIf(String value) {
        this._if = value;
    }

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelf(String value) {
        this.self = value;
    }

    /**
     * Gets the value of the unless property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnless() {
        return unless;
    }

    /**
     * Sets the value of the unless property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnless(String value) {
        this.unless = value;
    }

    /**
     * Gets the value of the onClick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnClick() {
        return onClick;
    }

    /**
     * Sets the value of the onClick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnClick(String value) {
        this.onClick = value;
    }

    /**
     * Gets the value of the onRightClick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnRightClick() {
        return onRightClick;
    }

    /**
     * Sets the value of the onRightClick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnRightClick(String value) {
        this.onRightClick = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
