//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.29 at 02:26:20 PM EEST 
//


package tr.com.agem.arya.metadata.arya.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for templateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="templateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{aryaportal.org}anyGroup"/>
 *         &lt;element ref="{aryaportal.org}area"/>
 *         &lt;element ref="{aryaportal.org}caption"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{aryaportal.org}rootAttrGroup"/>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="if" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="var" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "templateType", propOrder = {
    "attributeOrCustomAttributesOrVariables"
})
public class TemplateType {

    @XmlElementRefs({
        @XmlElementRef(name = "cell", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "button", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "checkbox", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "intbox", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datebox", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "a", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "window", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "space", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "variables", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "textbox", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "calendar", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "selectbox", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "attribute", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "caption", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "custom-attributes", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "template", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "radio", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "div", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "include", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idspace", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "label", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "area", namespace = "aryaportal.org", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "arya", namespace = "aryaportal.org", type = JAXBElement.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> attributeOrCustomAttributesOrVariables;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "src")
    protected String src;
    @XmlAttribute(name = "if")
    protected String _if;
    @XmlAttribute(name = "var")
    protected String var;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "onBookmarkChange")
    protected String onBookmarkChange;
    @XmlAttribute(name = "onClientInfo")
    protected String onClientInfo;

    /**
     * Gets the value of the attributeOrCustomAttributesOrVariables property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeOrCustomAttributesOrVariables property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeOrCustomAttributesOrVariables().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link SelectboxType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link CaptionType }{@code >}
     * {@link JAXBElement }{@code <}{@link TemplateType }{@code >}
     * {@link JAXBElement }{@code <}{@link IdspaceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AreaType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ButtonType }{@code >}
     * {@link JAXBElement }{@code <}{@link CheckboxType }{@code >}
     * {@link JAXBElement }{@code <}{@link DateboxType }{@code >}
     * {@link Element }
     * {@link JAXBElement }{@code <}{@link WindowType }{@code >}
     * {@link JAXBElement }{@code <}{@link SpaceType }{@code >}
     * {@link JAXBElement }{@code <}{@link VariablesType }{@code >}
     * {@link JAXBElement }{@code <}{@link TextboxType }{@code >}
     * {@link Object }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link RadioType }{@code >}
     * {@link JAXBElement }{@code <}{@link DivType }{@code >}
     * {@link JAXBElement }{@code <}{@link IncludeType }{@code >}
     * {@link JAXBElement }{@code <}{@link LabelType }{@code >}
     * {@link JAXBElement }{@code <}{@link AryaType }{@code >}
     * 
     * 
     */
    public List<Object> getAttributeOrCustomAttributesOrVariables() {
        if (attributeOrCustomAttributesOrVariables == null) {
            attributeOrCustomAttributesOrVariables = new ArrayList<Object>();
        }
        return this.attributeOrCustomAttributesOrVariables;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIf(String value) {
        this._if = value;
    }

    /**
     * Gets the value of the var property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVar() {
        return var;
    }

    /**
     * Sets the value of the var property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVar(String value) {
        this.var = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the onBookmarkChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnBookmarkChange() {
        return onBookmarkChange;
    }

    /**
     * Sets the value of the onBookmarkChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnBookmarkChange(String value) {
        this.onBookmarkChange = value;
    }

    /**
     * Gets the value of the onClientInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnClientInfo() {
        return onClientInfo;
    }

    /**
     * Sets the value of the onClientInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnClientInfo(String value) {
        this.onClientInfo = value;
    }

}
