//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 04:32:12 PM EEST 
//


package tr.com.agem.arya.metadata.zul.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for eastType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eastType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.zkoss.org/2005/zul}baseGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.zkoss.org/2005/zul}caption" minOccurs="0"/>
 *         &lt;group ref="{http://www.zkoss.org/2005/zul}anyGroupSingle" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.zkoss.org/2005/zul}xulElementAttrGroup"/>
 *       &lt;attribute name="flex" type="{http://www.zkoss.org/2005/zul}booleanType" />
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="splittable" type="{http://www.zkoss.org/2005/zul}booleanType" />
 *       &lt;attribute name="collapsible" type="{http://www.zkoss.org/2005/zul}booleanType" />
 *       &lt;attribute name="margins" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="open" type="{http://www.zkoss.org/2005/zul}booleanType" />
 *       &lt;attribute name="autoscroll" type="{http://www.zkoss.org/2005/zul}booleanType" />
 *       &lt;attribute name="border" type="{http://www.zkoss.org/2005/zul}layoutBorderAttrType" />
 *       &lt;attribute name="maxsize" type="{http://www.zkoss.org/2005/zul}intType" />
 *       &lt;attribute name="minsize" type="{http://www.zkoss.org/2005/zul}intType" />
 *       &lt;attribute name="onOpen" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eastType", propOrder = {
    "baseGroup",
    "caption",
    "a",
    "absolutelayout",
    "anchorlayout",
    "audio",
    "bandbox",
    "biglistbox",
    "borderlayout",
    "box",
    "button",
    "calendar",
    "calendars",
    "cardlayout",
    "cell",
    "chart",
    "charts",
    "checkbox",
    "chosenbox",
    "ckeditor",
    "colorbox",
    "columnlayout",
    "combobox",
    "combobutton",
    "datebox",
    "decimalbox",
    "div",
    "doublebox",
    "doublespinner",
    "dropupload",
    "fckeditor",
    "fisheyebar",
    "flash",
    "flashchart",
    "fusionchart",
    "frozen",
    "gmaps",
    "grid",
    "groupbox",
    "hbox",
    "hlayout",
    "html",
    "idspace",
    "iframe",
    "image",
    "imagemap",
    "include",
    "intbox",
    "label",
    "listbox",
    "longbox",
    "menubar",
    "menupopup",
    "navbar",
    "paging",
    "panel",
    "pivottable",
    "popup",
    "portallayout",
    "progressmeter",
    "radio",
    "radiogroup",
    "script",
    "scrollview",
    "selectbox",
    "separator",
    "slider",
    "space",
    "spinner",
    "styleType",
    "tabbox",
    "textbox",
    "timer",
    "timebox",
    "toolbar",
    "toolbarbutton",
    "tree",
    "vbox",
    "vlayout",
    "window",
    "zscript"
})
public class EastType {

    @XmlElementRefs({
        @XmlElementRef(name = "custom-attributes", namespace = "http://www.zkoss.org/2005/zul", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "variables", namespace = "http://www.zkoss.org/2005/zul", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "template", namespace = "http://www.zkoss.org/2005/zul", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "zk", namespace = "http://www.zkoss.org/2005/zul", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "attribute", namespace = "http://www.zkoss.org/2005/zul", type = JAXBElement.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> baseGroup;
    protected CaptionType caption;
    protected AType a;
    protected AbsolutelayoutType absolutelayout;
    protected AnchorlayoutType anchorlayout;
    protected AudioType audio;
    protected BandboxType bandbox;
    protected BiglistboxType biglistbox;
    protected BorderlayoutType borderlayout;
    protected BoxType box;
    protected ButtonType button;
    protected CalendarType calendar;
    protected CalendarsType calendars;
    protected CardlayoutType cardlayout;
    protected CellType cell;
    protected ChartType chart;
    protected ChartsType charts;
    protected CheckboxType checkbox;
    protected ChosenboxType chosenbox;
    protected CkeditorType ckeditor;
    protected ColorboxType colorbox;
    protected ColumnlayoutType columnlayout;
    protected ComboboxType combobox;
    protected CombobuttonType combobutton;
    protected DateboxType datebox;
    protected DecimalboxType decimalbox;
    protected DivType div;
    protected DoubleboxType doublebox;
    protected DoublespinnerType doublespinner;
    protected DropuploadType dropupload;
    protected FckeditorType fckeditor;
    protected FisheyebarType fisheyebar;
    protected FlashType flash;
    protected FlashchartType flashchart;
    protected FusionchartType fusionchart;
    protected FrozenType frozen;
    protected GmapsType gmaps;
    protected GridType grid;
    protected GroupboxType groupbox;
    protected HboxType hbox;
    protected HlayoutType hlayout;
    protected HtmlType html;
    protected IdspaceType idspace;
    protected IframeType iframe;
    protected ImageType image;
    protected ImagemapType imagemap;
    protected IncludeType include;
    protected IntboxType intbox;
    protected LabelType label;
    protected ListboxType listbox;
    protected LongboxType longbox;
    protected MenubarType menubar;
    protected MenupopupType menupopup;
    protected NavbarType navbar;
    protected PagingType paging;
    protected PanelType panel;
    protected PivottableType pivottable;
    protected PopupType popup;
    protected PortallayoutType portallayout;
    protected ProgressmeterType progressmeter;
    protected RadioType radio;
    protected RadiogroupType radiogroup;
    protected ScriptType script;
    protected ScrollviewType scrollview;
    protected SelectboxType selectbox;
    protected SeparatorType separator;
    protected SliderType slider;
    protected SpaceType space;
    protected SpinnerType spinner;
    protected StyleType styleType;
    protected TabboxType tabbox;
    protected TextboxType textbox;
    protected TimerType timer;
    protected TimeboxType timebox;
    protected ToolbarType toolbar;
    protected ToolbarbuttonType toolbarbutton;
    protected TreeType tree;
    protected VboxType vbox;
    protected VlayoutType vlayout;
    protected WindowType window;
    protected ZscriptType zscript;
    @XmlAttribute(name = "flex")
    protected String flex;
    @XmlAttribute(name = "size")
    protected String size;
    @XmlAttribute(name = "splittable")
    protected String splittable;
    @XmlAttribute(name = "collapsible")
    protected String collapsible;
    @XmlAttribute(name = "margins")
    protected String margins;
    @XmlAttribute(name = "open")
    protected String open;
    @XmlAttribute(name = "autoscroll")
    protected String autoscroll;
    @XmlAttribute(name = "border")
    protected String border;
    @XmlAttribute(name = "maxsize")
    protected String maxsize;
    @XmlAttribute(name = "minsize")
    protected String minsize;
    @XmlAttribute(name = "onOpen")
    protected String onOpen;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "context")
    protected String context;
    @XmlAttribute(name = "tooltip")
    protected String tooltip;
    @XmlAttribute(name = "onCtrlKey")
    protected String onCtrlKey;
    @XmlAttribute(name = "ctrlKeys")
    protected String ctrlKeys;
    @XmlAttribute(name = "width")
    protected String width;
    @XmlAttribute(name = "height")
    protected String height;
    @XmlAttribute(name = "sclass")
    protected String sclass;
    @XmlAttribute(name = "zclass")
    protected String zclass;
    @XmlAttribute(name = "style")
    protected String style;
    @XmlAttribute(name = "left")
    protected String left;
    @XmlAttribute(name = "top")
    protected String top;
    @XmlAttribute(name = "draggable")
    protected String draggable;
    @XmlAttribute(name = "droppable")
    protected String droppable;
    @XmlAttribute(name = "focus")
    protected String focus;
    @XmlAttribute(name = "tooltiptext")
    protected String tooltiptext;
    @XmlAttribute(name = "zindex")
    protected String zindex;
    @XmlAttribute(name = "renderdefer")
    protected String renderdefer;
    @XmlAttribute(name = "onCreate")
    protected String onCreate;
    @XmlAttribute(name = "onDrop")
    protected String onDrop;
    @XmlAttribute(name = "action")
    protected String action;
    @XmlAttribute(name = "hflex")
    protected String hflex;
    @XmlAttribute(name = "vflex")
    protected String vflex;
    @XmlAttribute(name = "apply")
    protected String apply;
    @XmlAttribute(name = "auService")
    protected String auService;
    @XmlAttribute(name = "autag")
    protected String autag;
    @XmlAttribute(name = "binder")
    protected String binder;
    @XmlAttribute(name = "children")
    protected String children;
    @XmlAttribute(name = "form")
    protected String form;
    @XmlAttribute(name = "forward")
    protected String forward;
    @XmlAttribute(name = "fulfill")
    protected String fulfill;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "mold")
    protected String mold;
    @XmlAttribute(name = "onFulfill")
    protected String onFulfill;
    @XmlAttribute(name = "stubonly")
    protected String stubonly;
    @XmlAttribute(name = "use")
    protected String use;
    @XmlAttribute(name = "viewModel")
    protected String viewModel;
    @XmlAttribute(name = "visible")
    protected String visible;
    @XmlAttribute(name = "forEach")
    protected String forEach;
    @XmlAttribute(name = "forEachBegin")
    protected String forEachBegin;
    @XmlAttribute(name = "forEachEnd")
    protected String forEachEnd;
    @XmlAttribute(name = "if")
    protected String _if;
    @XmlAttribute(name = "self")
    protected String self;
    @XmlAttribute(name = "unless")
    protected String unless;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the baseGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link JAXBElement }{@code <}{@link TemplateType }{@code >}
     * {@link JAXBElement }{@code <}{@link CustomAttributesType }{@code >}
     * {@link Object }
     * {@link JAXBElement }{@code <}{@link VariablesType }{@code >}
     * {@link JAXBElement }{@code <}{@link ZkType }{@code >}
     * {@link JAXBElement }{@code <}{@link AttributeType }{@code >}
     * 
     * 
     */
    public List<Object> getBaseGroup() {
        if (baseGroup == null) {
            baseGroup = new ArrayList<Object>();
        }
        return this.baseGroup;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link CaptionType }
     *     
     */
    public CaptionType getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaptionType }
     *     
     */
    public void setCaption(CaptionType value) {
        this.caption = value;
    }

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link AType }
     *     
     */
    public AType getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link AType }
     *     
     */
    public void setA(AType value) {
        this.a = value;
    }

    /**
     * Gets the value of the absolutelayout property.
     * 
     * @return
     *     possible object is
     *     {@link AbsolutelayoutType }
     *     
     */
    public AbsolutelayoutType getAbsolutelayout() {
        return absolutelayout;
    }

    /**
     * Sets the value of the absolutelayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbsolutelayoutType }
     *     
     */
    public void setAbsolutelayout(AbsolutelayoutType value) {
        this.absolutelayout = value;
    }

    /**
     * Gets the value of the anchorlayout property.
     * 
     * @return
     *     possible object is
     *     {@link AnchorlayoutType }
     *     
     */
    public AnchorlayoutType getAnchorlayout() {
        return anchorlayout;
    }

    /**
     * Sets the value of the anchorlayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnchorlayoutType }
     *     
     */
    public void setAnchorlayout(AnchorlayoutType value) {
        this.anchorlayout = value;
    }

    /**
     * Gets the value of the audio property.
     * 
     * @return
     *     possible object is
     *     {@link AudioType }
     *     
     */
    public AudioType getAudio() {
        return audio;
    }

    /**
     * Sets the value of the audio property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioType }
     *     
     */
    public void setAudio(AudioType value) {
        this.audio = value;
    }

    /**
     * Gets the value of the bandbox property.
     * 
     * @return
     *     possible object is
     *     {@link BandboxType }
     *     
     */
    public BandboxType getBandbox() {
        return bandbox;
    }

    /**
     * Sets the value of the bandbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link BandboxType }
     *     
     */
    public void setBandbox(BandboxType value) {
        this.bandbox = value;
    }

    /**
     * Gets the value of the biglistbox property.
     * 
     * @return
     *     possible object is
     *     {@link BiglistboxType }
     *     
     */
    public BiglistboxType getBiglistbox() {
        return biglistbox;
    }

    /**
     * Sets the value of the biglistbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link BiglistboxType }
     *     
     */
    public void setBiglistbox(BiglistboxType value) {
        this.biglistbox = value;
    }

    /**
     * Gets the value of the borderlayout property.
     * 
     * @return
     *     possible object is
     *     {@link BorderlayoutType }
     *     
     */
    public BorderlayoutType getBorderlayout() {
        return borderlayout;
    }

    /**
     * Sets the value of the borderlayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BorderlayoutType }
     *     
     */
    public void setBorderlayout(BorderlayoutType value) {
        this.borderlayout = value;
    }

    /**
     * Gets the value of the box property.
     * 
     * @return
     *     possible object is
     *     {@link BoxType }
     *     
     */
    public BoxType getBox() {
        return box;
    }

    /**
     * Sets the value of the box property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoxType }
     *     
     */
    public void setBox(BoxType value) {
        this.box = value;
    }

    /**
     * Gets the value of the button property.
     * 
     * @return
     *     possible object is
     *     {@link ButtonType }
     *     
     */
    public ButtonType getButton() {
        return button;
    }

    /**
     * Sets the value of the button property.
     * 
     * @param value
     *     allowed object is
     *     {@link ButtonType }
     *     
     */
    public void setButton(ButtonType value) {
        this.button = value;
    }

    /**
     * Gets the value of the calendar property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarType }
     *     
     */
    public CalendarType getCalendar() {
        return calendar;
    }

    /**
     * Sets the value of the calendar property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarType }
     *     
     */
    public void setCalendar(CalendarType value) {
        this.calendar = value;
    }

    /**
     * Gets the value of the calendars property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarsType }
     *     
     */
    public CalendarsType getCalendars() {
        return calendars;
    }

    /**
     * Sets the value of the calendars property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarsType }
     *     
     */
    public void setCalendars(CalendarsType value) {
        this.calendars = value;
    }

    /**
     * Gets the value of the cardlayout property.
     * 
     * @return
     *     possible object is
     *     {@link CardlayoutType }
     *     
     */
    public CardlayoutType getCardlayout() {
        return cardlayout;
    }

    /**
     * Sets the value of the cardlayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardlayoutType }
     *     
     */
    public void setCardlayout(CardlayoutType value) {
        this.cardlayout = value;
    }

    /**
     * Gets the value of the cell property.
     * 
     * @return
     *     possible object is
     *     {@link CellType }
     *     
     */
    public CellType getCell() {
        return cell;
    }

    /**
     * Sets the value of the cell property.
     * 
     * @param value
     *     allowed object is
     *     {@link CellType }
     *     
     */
    public void setCell(CellType value) {
        this.cell = value;
    }

    /**
     * Gets the value of the chart property.
     * 
     * @return
     *     possible object is
     *     {@link ChartType }
     *     
     */
    public ChartType getChart() {
        return chart;
    }

    /**
     * Sets the value of the chart property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartType }
     *     
     */
    public void setChart(ChartType value) {
        this.chart = value;
    }

    /**
     * Gets the value of the charts property.
     * 
     * @return
     *     possible object is
     *     {@link ChartsType }
     *     
     */
    public ChartsType getCharts() {
        return charts;
    }

    /**
     * Sets the value of the charts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartsType }
     *     
     */
    public void setCharts(ChartsType value) {
        this.charts = value;
    }

    /**
     * Gets the value of the checkbox property.
     * 
     * @return
     *     possible object is
     *     {@link CheckboxType }
     *     
     */
    public CheckboxType getCheckbox() {
        return checkbox;
    }

    /**
     * Sets the value of the checkbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckboxType }
     *     
     */
    public void setCheckbox(CheckboxType value) {
        this.checkbox = value;
    }

    /**
     * Gets the value of the chosenbox property.
     * 
     * @return
     *     possible object is
     *     {@link ChosenboxType }
     *     
     */
    public ChosenboxType getChosenbox() {
        return chosenbox;
    }

    /**
     * Sets the value of the chosenbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChosenboxType }
     *     
     */
    public void setChosenbox(ChosenboxType value) {
        this.chosenbox = value;
    }

    /**
     * Gets the value of the ckeditor property.
     * 
     * @return
     *     possible object is
     *     {@link CkeditorType }
     *     
     */
    public CkeditorType getCkeditor() {
        return ckeditor;
    }

    /**
     * Sets the value of the ckeditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CkeditorType }
     *     
     */
    public void setCkeditor(CkeditorType value) {
        this.ckeditor = value;
    }

    /**
     * Gets the value of the colorbox property.
     * 
     * @return
     *     possible object is
     *     {@link ColorboxType }
     *     
     */
    public ColorboxType getColorbox() {
        return colorbox;
    }

    /**
     * Sets the value of the colorbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorboxType }
     *     
     */
    public void setColorbox(ColorboxType value) {
        this.colorbox = value;
    }

    /**
     * Gets the value of the columnlayout property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnlayoutType }
     *     
     */
    public ColumnlayoutType getColumnlayout() {
        return columnlayout;
    }

    /**
     * Sets the value of the columnlayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnlayoutType }
     *     
     */
    public void setColumnlayout(ColumnlayoutType value) {
        this.columnlayout = value;
    }

    /**
     * Gets the value of the combobox property.
     * 
     * @return
     *     possible object is
     *     {@link ComboboxType }
     *     
     */
    public ComboboxType getCombobox() {
        return combobox;
    }

    /**
     * Sets the value of the combobox property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComboboxType }
     *     
     */
    public void setCombobox(ComboboxType value) {
        this.combobox = value;
    }

    /**
     * Gets the value of the combobutton property.
     * 
     * @return
     *     possible object is
     *     {@link CombobuttonType }
     *     
     */
    public CombobuttonType getCombobutton() {
        return combobutton;
    }

    /**
     * Sets the value of the combobutton property.
     * 
     * @param value
     *     allowed object is
     *     {@link CombobuttonType }
     *     
     */
    public void setCombobutton(CombobuttonType value) {
        this.combobutton = value;
    }

    /**
     * Gets the value of the datebox property.
     * 
     * @return
     *     possible object is
     *     {@link DateboxType }
     *     
     */
    public DateboxType getDatebox() {
        return datebox;
    }

    /**
     * Sets the value of the datebox property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateboxType }
     *     
     */
    public void setDatebox(DateboxType value) {
        this.datebox = value;
    }

    /**
     * Gets the value of the decimalbox property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalboxType }
     *     
     */
    public DecimalboxType getDecimalbox() {
        return decimalbox;
    }

    /**
     * Sets the value of the decimalbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalboxType }
     *     
     */
    public void setDecimalbox(DecimalboxType value) {
        this.decimalbox = value;
    }

    /**
     * Gets the value of the div property.
     * 
     * @return
     *     possible object is
     *     {@link DivType }
     *     
     */
    public DivType getDiv() {
        return div;
    }

    /**
     * Sets the value of the div property.
     * 
     * @param value
     *     allowed object is
     *     {@link DivType }
     *     
     */
    public void setDiv(DivType value) {
        this.div = value;
    }

    /**
     * Gets the value of the doublebox property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleboxType }
     *     
     */
    public DoubleboxType getDoublebox() {
        return doublebox;
    }

    /**
     * Sets the value of the doublebox property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleboxType }
     *     
     */
    public void setDoublebox(DoubleboxType value) {
        this.doublebox = value;
    }

    /**
     * Gets the value of the doublespinner property.
     * 
     * @return
     *     possible object is
     *     {@link DoublespinnerType }
     *     
     */
    public DoublespinnerType getDoublespinner() {
        return doublespinner;
    }

    /**
     * Sets the value of the doublespinner property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoublespinnerType }
     *     
     */
    public void setDoublespinner(DoublespinnerType value) {
        this.doublespinner = value;
    }

    /**
     * Gets the value of the dropupload property.
     * 
     * @return
     *     possible object is
     *     {@link DropuploadType }
     *     
     */
    public DropuploadType getDropupload() {
        return dropupload;
    }

    /**
     * Sets the value of the dropupload property.
     * 
     * @param value
     *     allowed object is
     *     {@link DropuploadType }
     *     
     */
    public void setDropupload(DropuploadType value) {
        this.dropupload = value;
    }

    /**
     * Gets the value of the fckeditor property.
     * 
     * @return
     *     possible object is
     *     {@link FckeditorType }
     *     
     */
    public FckeditorType getFckeditor() {
        return fckeditor;
    }

    /**
     * Sets the value of the fckeditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link FckeditorType }
     *     
     */
    public void setFckeditor(FckeditorType value) {
        this.fckeditor = value;
    }

    /**
     * Gets the value of the fisheyebar property.
     * 
     * @return
     *     possible object is
     *     {@link FisheyebarType }
     *     
     */
    public FisheyebarType getFisheyebar() {
        return fisheyebar;
    }

    /**
     * Sets the value of the fisheyebar property.
     * 
     * @param value
     *     allowed object is
     *     {@link FisheyebarType }
     *     
     */
    public void setFisheyebar(FisheyebarType value) {
        this.fisheyebar = value;
    }

    /**
     * Gets the value of the flash property.
     * 
     * @return
     *     possible object is
     *     {@link FlashType }
     *     
     */
    public FlashType getFlash() {
        return flash;
    }

    /**
     * Sets the value of the flash property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlashType }
     *     
     */
    public void setFlash(FlashType value) {
        this.flash = value;
    }

    /**
     * Gets the value of the flashchart property.
     * 
     * @return
     *     possible object is
     *     {@link FlashchartType }
     *     
     */
    public FlashchartType getFlashchart() {
        return flashchart;
    }

    /**
     * Sets the value of the flashchart property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlashchartType }
     *     
     */
    public void setFlashchart(FlashchartType value) {
        this.flashchart = value;
    }

    /**
     * Gets the value of the fusionchart property.
     * 
     * @return
     *     possible object is
     *     {@link FusionchartType }
     *     
     */
    public FusionchartType getFusionchart() {
        return fusionchart;
    }

    /**
     * Sets the value of the fusionchart property.
     * 
     * @param value
     *     allowed object is
     *     {@link FusionchartType }
     *     
     */
    public void setFusionchart(FusionchartType value) {
        this.fusionchart = value;
    }

    /**
     * Gets the value of the frozen property.
     * 
     * @return
     *     possible object is
     *     {@link FrozenType }
     *     
     */
    public FrozenType getFrozen() {
        return frozen;
    }

    /**
     * Sets the value of the frozen property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrozenType }
     *     
     */
    public void setFrozen(FrozenType value) {
        this.frozen = value;
    }

    /**
     * Gets the value of the gmaps property.
     * 
     * @return
     *     possible object is
     *     {@link GmapsType }
     *     
     */
    public GmapsType getGmaps() {
        return gmaps;
    }

    /**
     * Sets the value of the gmaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link GmapsType }
     *     
     */
    public void setGmaps(GmapsType value) {
        this.gmaps = value;
    }

    /**
     * Gets the value of the grid property.
     * 
     * @return
     *     possible object is
     *     {@link GridType }
     *     
     */
    public GridType getGrid() {
        return grid;
    }

    /**
     * Sets the value of the grid property.
     * 
     * @param value
     *     allowed object is
     *     {@link GridType }
     *     
     */
    public void setGrid(GridType value) {
        this.grid = value;
    }

    /**
     * Gets the value of the groupbox property.
     * 
     * @return
     *     possible object is
     *     {@link GroupboxType }
     *     
     */
    public GroupboxType getGroupbox() {
        return groupbox;
    }

    /**
     * Sets the value of the groupbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupboxType }
     *     
     */
    public void setGroupbox(GroupboxType value) {
        this.groupbox = value;
    }

    /**
     * Gets the value of the hbox property.
     * 
     * @return
     *     possible object is
     *     {@link HboxType }
     *     
     */
    public HboxType getHbox() {
        return hbox;
    }

    /**
     * Sets the value of the hbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link HboxType }
     *     
     */
    public void setHbox(HboxType value) {
        this.hbox = value;
    }

    /**
     * Gets the value of the hlayout property.
     * 
     * @return
     *     possible object is
     *     {@link HlayoutType }
     *     
     */
    public HlayoutType getHlayout() {
        return hlayout;
    }

    /**
     * Sets the value of the hlayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link HlayoutType }
     *     
     */
    public void setHlayout(HlayoutType value) {
        this.hlayout = value;
    }

    /**
     * Gets the value of the html property.
     * 
     * @return
     *     possible object is
     *     {@link HtmlType }
     *     
     */
    public HtmlType getHtml() {
        return html;
    }

    /**
     * Sets the value of the html property.
     * 
     * @param value
     *     allowed object is
     *     {@link HtmlType }
     *     
     */
    public void setHtml(HtmlType value) {
        this.html = value;
    }

    /**
     * Gets the value of the idspace property.
     * 
     * @return
     *     possible object is
     *     {@link IdspaceType }
     *     
     */
    public IdspaceType getIdspace() {
        return idspace;
    }

    /**
     * Sets the value of the idspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdspaceType }
     *     
     */
    public void setIdspace(IdspaceType value) {
        this.idspace = value;
    }

    /**
     * Gets the value of the iframe property.
     * 
     * @return
     *     possible object is
     *     {@link IframeType }
     *     
     */
    public IframeType getIframe() {
        return iframe;
    }

    /**
     * Sets the value of the iframe property.
     * 
     * @param value
     *     allowed object is
     *     {@link IframeType }
     *     
     */
    public void setIframe(IframeType value) {
        this.iframe = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link ImageType }
     *     
     */
    public ImageType getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageType }
     *     
     */
    public void setImage(ImageType value) {
        this.image = value;
    }

    /**
     * Gets the value of the imagemap property.
     * 
     * @return
     *     possible object is
     *     {@link ImagemapType }
     *     
     */
    public ImagemapType getImagemap() {
        return imagemap;
    }

    /**
     * Sets the value of the imagemap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagemapType }
     *     
     */
    public void setImagemap(ImagemapType value) {
        this.imagemap = value;
    }

    /**
     * Gets the value of the include property.
     * 
     * @return
     *     possible object is
     *     {@link IncludeType }
     *     
     */
    public IncludeType getInclude() {
        return include;
    }

    /**
     * Sets the value of the include property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludeType }
     *     
     */
    public void setInclude(IncludeType value) {
        this.include = value;
    }

    /**
     * Gets the value of the intbox property.
     * 
     * @return
     *     possible object is
     *     {@link IntboxType }
     *     
     */
    public IntboxType getIntbox() {
        return intbox;
    }

    /**
     * Sets the value of the intbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntboxType }
     *     
     */
    public void setIntbox(IntboxType value) {
        this.intbox = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link LabelType }
     *     
     */
    public LabelType getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelType }
     *     
     */
    public void setLabel(LabelType value) {
        this.label = value;
    }

    /**
     * Gets the value of the listbox property.
     * 
     * @return
     *     possible object is
     *     {@link ListboxType }
     *     
     */
    public ListboxType getListbox() {
        return listbox;
    }

    /**
     * Sets the value of the listbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListboxType }
     *     
     */
    public void setListbox(ListboxType value) {
        this.listbox = value;
    }

    /**
     * Gets the value of the longbox property.
     * 
     * @return
     *     possible object is
     *     {@link LongboxType }
     *     
     */
    public LongboxType getLongbox() {
        return longbox;
    }

    /**
     * Sets the value of the longbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongboxType }
     *     
     */
    public void setLongbox(LongboxType value) {
        this.longbox = value;
    }

    /**
     * Gets the value of the menubar property.
     * 
     * @return
     *     possible object is
     *     {@link MenubarType }
     *     
     */
    public MenubarType getMenubar() {
        return menubar;
    }

    /**
     * Sets the value of the menubar property.
     * 
     * @param value
     *     allowed object is
     *     {@link MenubarType }
     *     
     */
    public void setMenubar(MenubarType value) {
        this.menubar = value;
    }

    /**
     * Gets the value of the menupopup property.
     * 
     * @return
     *     possible object is
     *     {@link MenupopupType }
     *     
     */
    public MenupopupType getMenupopup() {
        return menupopup;
    }

    /**
     * Sets the value of the menupopup property.
     * 
     * @param value
     *     allowed object is
     *     {@link MenupopupType }
     *     
     */
    public void setMenupopup(MenupopupType value) {
        this.menupopup = value;
    }

    /**
     * Gets the value of the navbar property.
     * 
     * @return
     *     possible object is
     *     {@link NavbarType }
     *     
     */
    public NavbarType getNavbar() {
        return navbar;
    }

    /**
     * Sets the value of the navbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavbarType }
     *     
     */
    public void setNavbar(NavbarType value) {
        this.navbar = value;
    }

    /**
     * Gets the value of the paging property.
     * 
     * @return
     *     possible object is
     *     {@link PagingType }
     *     
     */
    public PagingType getPaging() {
        return paging;
    }

    /**
     * Sets the value of the paging property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagingType }
     *     
     */
    public void setPaging(PagingType value) {
        this.paging = value;
    }

    /**
     * Gets the value of the panel property.
     * 
     * @return
     *     possible object is
     *     {@link PanelType }
     *     
     */
    public PanelType getPanel() {
        return panel;
    }

    /**
     * Sets the value of the panel property.
     * 
     * @param value
     *     allowed object is
     *     {@link PanelType }
     *     
     */
    public void setPanel(PanelType value) {
        this.panel = value;
    }

    /**
     * Gets the value of the pivottable property.
     * 
     * @return
     *     possible object is
     *     {@link PivottableType }
     *     
     */
    public PivottableType getPivottable() {
        return pivottable;
    }

    /**
     * Sets the value of the pivottable property.
     * 
     * @param value
     *     allowed object is
     *     {@link PivottableType }
     *     
     */
    public void setPivottable(PivottableType value) {
        this.pivottable = value;
    }

    /**
     * Gets the value of the popup property.
     * 
     * @return
     *     possible object is
     *     {@link PopupType }
     *     
     */
    public PopupType getPopup() {
        return popup;
    }

    /**
     * Sets the value of the popup property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopupType }
     *     
     */
    public void setPopup(PopupType value) {
        this.popup = value;
    }

    /**
     * Gets the value of the portallayout property.
     * 
     * @return
     *     possible object is
     *     {@link PortallayoutType }
     *     
     */
    public PortallayoutType getPortallayout() {
        return portallayout;
    }

    /**
     * Sets the value of the portallayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortallayoutType }
     *     
     */
    public void setPortallayout(PortallayoutType value) {
        this.portallayout = value;
    }

    /**
     * Gets the value of the progressmeter property.
     * 
     * @return
     *     possible object is
     *     {@link ProgressmeterType }
     *     
     */
    public ProgressmeterType getProgressmeter() {
        return progressmeter;
    }

    /**
     * Sets the value of the progressmeter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgressmeterType }
     *     
     */
    public void setProgressmeter(ProgressmeterType value) {
        this.progressmeter = value;
    }

    /**
     * Gets the value of the radio property.
     * 
     * @return
     *     possible object is
     *     {@link RadioType }
     *     
     */
    public RadioType getRadio() {
        return radio;
    }

    /**
     * Sets the value of the radio property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadioType }
     *     
     */
    public void setRadio(RadioType value) {
        this.radio = value;
    }

    /**
     * Gets the value of the radiogroup property.
     * 
     * @return
     *     possible object is
     *     {@link RadiogroupType }
     *     
     */
    public RadiogroupType getRadiogroup() {
        return radiogroup;
    }

    /**
     * Sets the value of the radiogroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadiogroupType }
     *     
     */
    public void setRadiogroup(RadiogroupType value) {
        this.radiogroup = value;
    }

    /**
     * Gets the value of the script property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptType }
     *     
     */
    public ScriptType getScript() {
        return script;
    }

    /**
     * Sets the value of the script property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptType }
     *     
     */
    public void setScript(ScriptType value) {
        this.script = value;
    }

    /**
     * Gets the value of the scrollview property.
     * 
     * @return
     *     possible object is
     *     {@link ScrollviewType }
     *     
     */
    public ScrollviewType getScrollview() {
        return scrollview;
    }

    /**
     * Sets the value of the scrollview property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScrollviewType }
     *     
     */
    public void setScrollview(ScrollviewType value) {
        this.scrollview = value;
    }

    /**
     * Gets the value of the selectbox property.
     * 
     * @return
     *     possible object is
     *     {@link SelectboxType }
     *     
     */
    public SelectboxType getSelectbox() {
        return selectbox;
    }

    /**
     * Sets the value of the selectbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectboxType }
     *     
     */
    public void setSelectbox(SelectboxType value) {
        this.selectbox = value;
    }

    /**
     * Gets the value of the separator property.
     * 
     * @return
     *     possible object is
     *     {@link SeparatorType }
     *     
     */
    public SeparatorType getSeparator() {
        return separator;
    }

    /**
     * Sets the value of the separator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeparatorType }
     *     
     */
    public void setSeparator(SeparatorType value) {
        this.separator = value;
    }

    /**
     * Gets the value of the slider property.
     * 
     * @return
     *     possible object is
     *     {@link SliderType }
     *     
     */
    public SliderType getSlider() {
        return slider;
    }

    /**
     * Sets the value of the slider property.
     * 
     * @param value
     *     allowed object is
     *     {@link SliderType }
     *     
     */
    public void setSlider(SliderType value) {
        this.slider = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link SpaceType }
     *     
     */
    public SpaceType getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpaceType }
     *     
     */
    public void setSpace(SpaceType value) {
        this.space = value;
    }

    /**
     * Gets the value of the spinner property.
     * 
     * @return
     *     possible object is
     *     {@link SpinnerType }
     *     
     */
    public SpinnerType getSpinner() {
        return spinner;
    }

    /**
     * Sets the value of the spinner property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpinnerType }
     *     
     */
    public void setSpinner(SpinnerType value) {
        this.spinner = value;
    }

    /**
     * Gets the value of the styleType property.
     * 
     * @return
     *     possible object is
     *     {@link StyleType }
     *     
     */
    public StyleType getStyleType() {
        return styleType;
    }

    /**
     * Sets the value of the styleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StyleType }
     *     
     */
    public void setStyleType(StyleType value) {
        this.styleType = value;
    }

    /**
     * Gets the value of the tabbox property.
     * 
     * @return
     *     possible object is
     *     {@link TabboxType }
     *     
     */
    public TabboxType getTabbox() {
        return tabbox;
    }

    /**
     * Sets the value of the tabbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link TabboxType }
     *     
     */
    public void setTabbox(TabboxType value) {
        this.tabbox = value;
    }

    /**
     * Gets the value of the textbox property.
     * 
     * @return
     *     possible object is
     *     {@link TextboxType }
     *     
     */
    public TextboxType getTextbox() {
        return textbox;
    }

    /**
     * Sets the value of the textbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextboxType }
     *     
     */
    public void setTextbox(TextboxType value) {
        this.textbox = value;
    }

    /**
     * Gets the value of the timer property.
     * 
     * @return
     *     possible object is
     *     {@link TimerType }
     *     
     */
    public TimerType getTimer() {
        return timer;
    }

    /**
     * Sets the value of the timer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimerType }
     *     
     */
    public void setTimer(TimerType value) {
        this.timer = value;
    }

    /**
     * Gets the value of the timebox property.
     * 
     * @return
     *     possible object is
     *     {@link TimeboxType }
     *     
     */
    public TimeboxType getTimebox() {
        return timebox;
    }

    /**
     * Sets the value of the timebox property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeboxType }
     *     
     */
    public void setTimebox(TimeboxType value) {
        this.timebox = value;
    }

    /**
     * Gets the value of the toolbar property.
     * 
     * @return
     *     possible object is
     *     {@link ToolbarType }
     *     
     */
    public ToolbarType getToolbar() {
        return toolbar;
    }

    /**
     * Sets the value of the toolbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolbarType }
     *     
     */
    public void setToolbar(ToolbarType value) {
        this.toolbar = value;
    }

    /**
     * Gets the value of the toolbarbutton property.
     * 
     * @return
     *     possible object is
     *     {@link ToolbarbuttonType }
     *     
     */
    public ToolbarbuttonType getToolbarbutton() {
        return toolbarbutton;
    }

    /**
     * Sets the value of the toolbarbutton property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolbarbuttonType }
     *     
     */
    public void setToolbarbutton(ToolbarbuttonType value) {
        this.toolbarbutton = value;
    }

    /**
     * Gets the value of the tree property.
     * 
     * @return
     *     possible object is
     *     {@link TreeType }
     *     
     */
    public TreeType getTree() {
        return tree;
    }

    /**
     * Sets the value of the tree property.
     * 
     * @param value
     *     allowed object is
     *     {@link TreeType }
     *     
     */
    public void setTree(TreeType value) {
        this.tree = value;
    }

    /**
     * Gets the value of the vbox property.
     * 
     * @return
     *     possible object is
     *     {@link VboxType }
     *     
     */
    public VboxType getVbox() {
        return vbox;
    }

    /**
     * Sets the value of the vbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link VboxType }
     *     
     */
    public void setVbox(VboxType value) {
        this.vbox = value;
    }

    /**
     * Gets the value of the vlayout property.
     * 
     * @return
     *     possible object is
     *     {@link VlayoutType }
     *     
     */
    public VlayoutType getVlayout() {
        return vlayout;
    }

    /**
     * Sets the value of the vlayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link VlayoutType }
     *     
     */
    public void setVlayout(VlayoutType value) {
        this.vlayout = value;
    }

    /**
     * Gets the value of the window property.
     * 
     * @return
     *     possible object is
     *     {@link WindowType }
     *     
     */
    public WindowType getWindow() {
        return window;
    }

    /**
     * Sets the value of the window property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowType }
     *     
     */
    public void setWindow(WindowType value) {
        this.window = value;
    }

    /**
     * Gets the value of the zscript property.
     * 
     * @return
     *     possible object is
     *     {@link ZscriptType }
     *     
     */
    public ZscriptType getZscript() {
        return zscript;
    }

    /**
     * Sets the value of the zscript property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZscriptType }
     *     
     */
    public void setZscript(ZscriptType value) {
        this.zscript = value;
    }

    /**
     * Gets the value of the flex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlex() {
        return flex;
    }

    /**
     * Sets the value of the flex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlex(String value) {
        this.flex = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the splittable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSplittable() {
        return splittable;
    }

    /**
     * Sets the value of the splittable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSplittable(String value) {
        this.splittable = value;
    }

    /**
     * Gets the value of the collapsible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollapsible() {
        return collapsible;
    }

    /**
     * Sets the value of the collapsible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollapsible(String value) {
        this.collapsible = value;
    }

    /**
     * Gets the value of the margins property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMargins() {
        return margins;
    }

    /**
     * Sets the value of the margins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMargins(String value) {
        this.margins = value;
    }

    /**
     * Gets the value of the open property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpen() {
        return open;
    }

    /**
     * Sets the value of the open property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpen(String value) {
        this.open = value;
    }

    /**
     * Gets the value of the autoscroll property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoscroll() {
        return autoscroll;
    }

    /**
     * Sets the value of the autoscroll property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoscroll(String value) {
        this.autoscroll = value;
    }

    /**
     * Gets the value of the border property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorder() {
        return border;
    }

    /**
     * Sets the value of the border property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorder(String value) {
        this.border = value;
    }

    /**
     * Gets the value of the maxsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxsize() {
        return maxsize;
    }

    /**
     * Sets the value of the maxsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxsize(String value) {
        this.maxsize = value;
    }

    /**
     * Gets the value of the minsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinsize() {
        return minsize;
    }

    /**
     * Sets the value of the minsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinsize(String value) {
        this.minsize = value;
    }

    /**
     * Gets the value of the onOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnOpen() {
        return onOpen;
    }

    /**
     * Sets the value of the onOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnOpen(String value) {
        this.onOpen = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContext(String value) {
        this.context = value;
    }

    /**
     * Gets the value of the tooltip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTooltip() {
        return tooltip;
    }

    /**
     * Sets the value of the tooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTooltip(String value) {
        this.tooltip = value;
    }

    /**
     * Gets the value of the onCtrlKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnCtrlKey() {
        return onCtrlKey;
    }

    /**
     * Sets the value of the onCtrlKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnCtrlKey(String value) {
        this.onCtrlKey = value;
    }

    /**
     * Gets the value of the ctrlKeys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtrlKeys() {
        return ctrlKeys;
    }

    /**
     * Sets the value of the ctrlKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtrlKeys(String value) {
        this.ctrlKeys = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the sclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSclass() {
        return sclass;
    }

    /**
     * Sets the value of the sclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSclass(String value) {
        this.sclass = value;
    }

    /**
     * Gets the value of the zclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZclass() {
        return zclass;
    }

    /**
     * Sets the value of the zclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZclass(String value) {
        this.zclass = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the left property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeft() {
        return left;
    }

    /**
     * Sets the value of the left property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeft(String value) {
        this.left = value;
    }

    /**
     * Gets the value of the top property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTop() {
        return top;
    }

    /**
     * Sets the value of the top property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTop(String value) {
        this.top = value;
    }

    /**
     * Gets the value of the draggable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDraggable() {
        return draggable;
    }

    /**
     * Sets the value of the draggable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDraggable(String value) {
        this.draggable = value;
    }

    /**
     * Gets the value of the droppable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDroppable() {
        return droppable;
    }

    /**
     * Sets the value of the droppable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDroppable(String value) {
        this.droppable = value;
    }

    /**
     * Gets the value of the focus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFocus() {
        return focus;
    }

    /**
     * Sets the value of the focus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFocus(String value) {
        this.focus = value;
    }

    /**
     * Gets the value of the tooltiptext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTooltiptext() {
        return tooltiptext;
    }

    /**
     * Sets the value of the tooltiptext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTooltiptext(String value) {
        this.tooltiptext = value;
    }

    /**
     * Gets the value of the zindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZindex() {
        return zindex;
    }

    /**
     * Sets the value of the zindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZindex(String value) {
        this.zindex = value;
    }

    /**
     * Gets the value of the renderdefer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenderdefer() {
        return renderdefer;
    }

    /**
     * Sets the value of the renderdefer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenderdefer(String value) {
        this.renderdefer = value;
    }

    /**
     * Gets the value of the onCreate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnCreate() {
        return onCreate;
    }

    /**
     * Sets the value of the onCreate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnCreate(String value) {
        this.onCreate = value;
    }

    /**
     * Gets the value of the onDrop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnDrop() {
        return onDrop;
    }

    /**
     * Sets the value of the onDrop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnDrop(String value) {
        this.onDrop = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the hflex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHflex() {
        return hflex;
    }

    /**
     * Sets the value of the hflex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHflex(String value) {
        this.hflex = value;
    }

    /**
     * Gets the value of the vflex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVflex() {
        return vflex;
    }

    /**
     * Sets the value of the vflex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVflex(String value) {
        this.vflex = value;
    }

    /**
     * Gets the value of the apply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApply() {
        return apply;
    }

    /**
     * Sets the value of the apply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApply(String value) {
        this.apply = value;
    }

    /**
     * Gets the value of the auService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuService() {
        return auService;
    }

    /**
     * Sets the value of the auService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuService(String value) {
        this.auService = value;
    }

    /**
     * Gets the value of the autag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutag() {
        return autag;
    }

    /**
     * Sets the value of the autag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutag(String value) {
        this.autag = value;
    }

    /**
     * Gets the value of the binder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinder() {
        return binder;
    }

    /**
     * Sets the value of the binder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinder(String value) {
        this.binder = value;
    }

    /**
     * Gets the value of the children property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildren(String value) {
        this.children = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForm(String value) {
        this.form = value;
    }

    /**
     * Gets the value of the forward property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForward() {
        return forward;
    }

    /**
     * Sets the value of the forward property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForward(String value) {
        this.forward = value;
    }

    /**
     * Gets the value of the fulfill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfill() {
        return fulfill;
    }

    /**
     * Sets the value of the fulfill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfill(String value) {
        this.fulfill = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the mold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMold() {
        return mold;
    }

    /**
     * Sets the value of the mold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMold(String value) {
        this.mold = value;
    }

    /**
     * Gets the value of the onFulfill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnFulfill() {
        return onFulfill;
    }

    /**
     * Sets the value of the onFulfill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnFulfill(String value) {
        this.onFulfill = value;
    }

    /**
     * Gets the value of the stubonly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStubonly() {
        return stubonly;
    }

    /**
     * Sets the value of the stubonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStubonly(String value) {
        this.stubonly = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUse() {
        return use;
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUse(String value) {
        this.use = value;
    }

    /**
     * Gets the value of the viewModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewModel() {
        return viewModel;
    }

    /**
     * Sets the value of the viewModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewModel(String value) {
        this.viewModel = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the forEach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForEach() {
        return forEach;
    }

    /**
     * Sets the value of the forEach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForEach(String value) {
        this.forEach = value;
    }

    /**
     * Gets the value of the forEachBegin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForEachBegin() {
        return forEachBegin;
    }

    /**
     * Sets the value of the forEachBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForEachBegin(String value) {
        this.forEachBegin = value;
    }

    /**
     * Gets the value of the forEachEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForEachEnd() {
        return forEachEnd;
    }

    /**
     * Sets the value of the forEachEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForEachEnd(String value) {
        this.forEachEnd = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIf(String value) {
        this._if = value;
    }

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelf(String value) {
        this.self = value;
    }

    /**
     * Gets the value of the unless property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnless() {
        return unless;
    }

    /**
     * Sets the value of the unless property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnless(String value) {
        this.unless = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
