//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 04:32:12 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zkoss.org/2005/zul", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tr.com.agem.arya.metadata.zul.impl;
