//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.03 at 11:04:58 AM EEST 
//


package tr.com.agem.arya.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for browsertypeAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="browsertypeAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="content"/>
 *     &lt;enumeration value="content-primary"/>
 *     &lt;enumeration value="content-targetablebrowser"/>
 *     &lt;enumeration value="chrome"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "browsertypeAttributeType")
@XmlEnum
public enum BrowsertypeAttributeType {


    /**
     * content: A browser for content. The content that is loaded inside the browser is not allowed to access the chrome above it.
     * 
     */
    @XmlEnumValue("content")
    CONTENT("content"),

    /**
     * content-primary: The primary browser for content. The content that is loaded inside the browser is not allowed to access the chrome above it. For instance, in a web browser, this would be the element that displays the web page. The window for the primary content can be retrieved more conveniently using window.content.
     * 
     */
    @XmlEnumValue("content-primary")
    CONTENT_PRIMARY("content-primary"),

    /**
     * content-targetable: One browser among many for content. The content that is loaded inside the browser is not allowed to access the chrome above it. This is the preferred value for any browser element in an application that will use multiple browsers of equal privileges and is unselected at the moment.
     * 
     */
    @XmlEnumValue("content-targetablebrowser")
    CONTENT_TARGETABLEBROWSER("content-targetablebrowser"),

    /**
     * chrome: (default) A browser, intended to be used for loading privileged content using a chrome:// URI. Don't use for content from web, as this may cause serious security problems!
     * 
     */
    @XmlEnumValue("chrome")
    CHROME("chrome");
    private final String value;

    BrowsertypeAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BrowsertypeAttributeType fromValue(String v) {
        for (BrowsertypeAttributeType c: BrowsertypeAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
