//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.03 at 11:04:58 AM EEST 
//


package tr.com.agem.arya.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dlgtypeAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dlgtypeAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="accept"/>
 *     &lt;enumeration value="cancel"/>
 *     &lt;enumeration value="help"/>
 *     &lt;enumeration value="disclosure"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dlgtypeAttributeType")
@XmlEnum
public enum DlgtypeAttributeType {


    /**
     * 
     *             accept: The OK button, which will accept the changes when pressed.
     *           
     * 
     */
    @XmlEnumValue("accept")
    ACCEPT("accept"),

    /**
     * 
     *             cancel: The cancel button which will cancel the operation.
     *           
     * 
     */
    @XmlEnumValue("cancel")
    CANCEL("cancel"),

    /**
     * 
     *             help: A help button for displaying help about the dialog.
     *           
     * 
     */
    @XmlEnumValue("help")
    HELP("help"),

    /**
     * 
     *             disclosure: A button to show more information. This might be a button or a disclosure triangle.
     *           
     * 
     */
    @XmlEnumValue("disclosure")
    DISCLOSURE("disclosure");
    private final String value;

    DlgtypeAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DlgtypeAttributeType fromValue(String v) {
        for (DlgtypeAttributeType c: DlgtypeAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
