//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.03 at 11:04:58 AM EEST 
//


package tr.com.agem.arya.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for htmlColorList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="htmlColorList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AliceBlue"/>
 *     &lt;enumeration value="AntiqueWhite"/>
 *     &lt;enumeration value="Aqua"/>
 *     &lt;enumeration value="Aquamarine"/>
 *     &lt;enumeration value="Azure"/>
 *     &lt;enumeration value="Beige"/>
 *     &lt;enumeration value="Bisque"/>
 *     &lt;enumeration value="Black"/>
 *     &lt;enumeration value="BlanchedAlmond"/>
 *     &lt;enumeration value="Blue"/>
 *     &lt;enumeration value="BlueViolet"/>
 *     &lt;enumeration value="Brown"/>
 *     &lt;enumeration value="BurlyWood"/>
 *     &lt;enumeration value="CadetBlue"/>
 *     &lt;enumeration value="Chartreuse"/>
 *     &lt;enumeration value="Chocolate"/>
 *     &lt;enumeration value="Coral"/>
 *     &lt;enumeration value="CornflowerBlue"/>
 *     &lt;enumeration value="Cornsilk"/>
 *     &lt;enumeration value="Crimson"/>
 *     &lt;enumeration value="Cyan"/>
 *     &lt;enumeration value="DarkBlue"/>
 *     &lt;enumeration value="DarkCyan"/>
 *     &lt;enumeration value="DarkGoldenRod"/>
 *     &lt;enumeration value="DarkGray"/>
 *     &lt;enumeration value="DarkGrey"/>
 *     &lt;enumeration value="DarkGreen"/>
 *     &lt;enumeration value="DarkKhaki"/>
 *     &lt;enumeration value="DarkMagenta"/>
 *     &lt;enumeration value="DarkOliveGreen"/>
 *     &lt;enumeration value="Darkorange"/>
 *     &lt;enumeration value="DarkOrchid"/>
 *     &lt;enumeration value="DarkRed"/>
 *     &lt;enumeration value="DarkSalmon"/>
 *     &lt;enumeration value="DarkSeaGreen"/>
 *     &lt;enumeration value="DarkSlateBlue"/>
 *     &lt;enumeration value="DarkSlateGray"/>
 *     &lt;enumeration value="DarkSlateGrey"/>
 *     &lt;enumeration value="DarkTurquoise"/>
 *     &lt;enumeration value="DarkViolet"/>
 *     &lt;enumeration value="DeepPink"/>
 *     &lt;enumeration value="DeepSkyBlue"/>
 *     &lt;enumeration value="DimGray"/>
 *     &lt;enumeration value="DimGrey"/>
 *     &lt;enumeration value="DodgerBlue"/>
 *     &lt;enumeration value="FireBrick"/>
 *     &lt;enumeration value="FloralWhite"/>
 *     &lt;enumeration value="ForestGreen"/>
 *     &lt;enumeration value="Fuchsia"/>
 *     &lt;enumeration value="Gainsboro"/>
 *     &lt;enumeration value="GhostWhite"/>
 *     &lt;enumeration value="Gold"/>
 *     &lt;enumeration value="GoldenRod"/>
 *     &lt;enumeration value="Gray"/>
 *     &lt;enumeration value="Grey"/>
 *     &lt;enumeration value="Green"/>
 *     &lt;enumeration value="GreenYellow"/>
 *     &lt;enumeration value="HoneyDew"/>
 *     &lt;enumeration value="HotPink"/>
 *     &lt;enumeration value="IndianRed"/>
 *     &lt;enumeration value="Indigo"/>
 *     &lt;enumeration value="Ivory"/>
 *     &lt;enumeration value="Khaki"/>
 *     &lt;enumeration value="Lavender"/>
 *     &lt;enumeration value="LavenderBlush"/>
 *     &lt;enumeration value="LawnGreen"/>
 *     &lt;enumeration value="LemonChiffon"/>
 *     &lt;enumeration value="LightBlue"/>
 *     &lt;enumeration value="LightCoral"/>
 *     &lt;enumeration value="LightCyan"/>
 *     &lt;enumeration value="LightGoldenRodYellow"/>
 *     &lt;enumeration value="LightGray"/>
 *     &lt;enumeration value="LightGrey"/>
 *     &lt;enumeration value="LightGreen"/>
 *     &lt;enumeration value="LightPink"/>
 *     &lt;enumeration value="LightSalmon"/>
 *     &lt;enumeration value="LightSeaGreen"/>
 *     &lt;enumeration value="LightSkyBlue"/>
 *     &lt;enumeration value="LightSlateGray"/>
 *     &lt;enumeration value="LightSlateGrey"/>
 *     &lt;enumeration value="LightSteelBlue"/>
 *     &lt;enumeration value="LightYellow"/>
 *     &lt;enumeration value="Lime"/>
 *     &lt;enumeration value="LimeGreen"/>
 *     &lt;enumeration value="Linen"/>
 *     &lt;enumeration value="Magenta"/>
 *     &lt;enumeration value="Maroon"/>
 *     &lt;enumeration value="MediumAquaMarine"/>
 *     &lt;enumeration value="MediumBlue"/>
 *     &lt;enumeration value="MediumOrchid"/>
 *     &lt;enumeration value="MediumPurple"/>
 *     &lt;enumeration value="MediumSeaGreen"/>
 *     &lt;enumeration value="MediumSlateBlue"/>
 *     &lt;enumeration value="MediumSpringGreen"/>
 *     &lt;enumeration value="MediumTurquoise"/>
 *     &lt;enumeration value="MediumVioletRed"/>
 *     &lt;enumeration value="MidnightBlue"/>
 *     &lt;enumeration value="MintCream"/>
 *     &lt;enumeration value="MistyRose"/>
 *     &lt;enumeration value="Moccasin"/>
 *     &lt;enumeration value="NavajoWhite"/>
 *     &lt;enumeration value="Navy"/>
 *     &lt;enumeration value="OldLace"/>
 *     &lt;enumeration value="Olive"/>
 *     &lt;enumeration value="OliveDrab"/>
 *     &lt;enumeration value="Orange"/>
 *     &lt;enumeration value="OrangeRed"/>
 *     &lt;enumeration value="Orchid"/>
 *     &lt;enumeration value="PaleGoldenRod"/>
 *     &lt;enumeration value="PaleGreen"/>
 *     &lt;enumeration value="PaleTurquoise"/>
 *     &lt;enumeration value="PaleVioletRed"/>
 *     &lt;enumeration value="PapayaWhip"/>
 *     &lt;enumeration value="PeachPuff"/>
 *     &lt;enumeration value="Peru"/>
 *     &lt;enumeration value="Pink"/>
 *     &lt;enumeration value="Plum"/>
 *     &lt;enumeration value="PowderBlue"/>
 *     &lt;enumeration value="Purple"/>
 *     &lt;enumeration value="Red"/>
 *     &lt;enumeration value="RosyBrown"/>
 *     &lt;enumeration value="RoyalBlue"/>
 *     &lt;enumeration value="SaddleBrown"/>
 *     &lt;enumeration value="Salmon"/>
 *     &lt;enumeration value="SandyBrown"/>
 *     &lt;enumeration value="SeaGreen"/>
 *     &lt;enumeration value="SeaShell"/>
 *     &lt;enumeration value="Sienna"/>
 *     &lt;enumeration value="Silver"/>
 *     &lt;enumeration value="SkyBlue"/>
 *     &lt;enumeration value="SlateBlue"/>
 *     &lt;enumeration value="SlateGray"/>
 *     &lt;enumeration value="SlateGrey"/>
 *     &lt;enumeration value="Snow"/>
 *     &lt;enumeration value="SpringGreen"/>
 *     &lt;enumeration value="SteelBlue"/>
 *     &lt;enumeration value="Tan"/>
 *     &lt;enumeration value="Teal"/>
 *     &lt;enumeration value="Thistle"/>
 *     &lt;enumeration value="Tomato"/>
 *     &lt;enumeration value="Turquoise"/>
 *     &lt;enumeration value="Violet"/>
 *     &lt;enumeration value="Wheat"/>
 *     &lt;enumeration value="White"/>
 *     &lt;enumeration value="WhiteSmoke"/>
 *     &lt;enumeration value="Yellow"/>
 *     &lt;enumeration value="YellowGreen"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "htmlColorList")
@XmlEnum
public enum HtmlColorList {

    @XmlEnumValue("AliceBlue")
    ALICE_BLUE("AliceBlue"),
    @XmlEnumValue("AntiqueWhite")
    ANTIQUE_WHITE("AntiqueWhite"),
    @XmlEnumValue("Aqua")
    AQUA("Aqua"),
    @XmlEnumValue("Aquamarine")
    AQUAMARINE("Aquamarine"),
    @XmlEnumValue("Azure")
    AZURE("Azure"),
    @XmlEnumValue("Beige")
    BEIGE("Beige"),
    @XmlEnumValue("Bisque")
    BISQUE("Bisque"),
    @XmlEnumValue("Black")
    BLACK("Black"),
    @XmlEnumValue("BlanchedAlmond")
    BLANCHED_ALMOND("BlanchedAlmond"),
    @XmlEnumValue("Blue")
    BLUE("Blue"),
    @XmlEnumValue("BlueViolet")
    BLUE_VIOLET("BlueViolet"),
    @XmlEnumValue("Brown")
    BROWN("Brown"),
    @XmlEnumValue("BurlyWood")
    BURLY_WOOD("BurlyWood"),
    @XmlEnumValue("CadetBlue")
    CADET_BLUE("CadetBlue"),
    @XmlEnumValue("Chartreuse")
    CHARTREUSE("Chartreuse"),
    @XmlEnumValue("Chocolate")
    CHOCOLATE("Chocolate"),
    @XmlEnumValue("Coral")
    CORAL("Coral"),
    @XmlEnumValue("CornflowerBlue")
    CORNFLOWER_BLUE("CornflowerBlue"),
    @XmlEnumValue("Cornsilk")
    CORNSILK("Cornsilk"),
    @XmlEnumValue("Crimson")
    CRIMSON("Crimson"),
    @XmlEnumValue("Cyan")
    CYAN("Cyan"),
    @XmlEnumValue("DarkBlue")
    DARK_BLUE("DarkBlue"),
    @XmlEnumValue("DarkCyan")
    DARK_CYAN("DarkCyan"),
    @XmlEnumValue("DarkGoldenRod")
    DARK_GOLDEN_ROD("DarkGoldenRod"),
    @XmlEnumValue("DarkGray")
    DARK_GRAY("DarkGray"),
    @XmlEnumValue("DarkGrey")
    DARK_GREY("DarkGrey"),
    @XmlEnumValue("DarkGreen")
    DARK_GREEN("DarkGreen"),
    @XmlEnumValue("DarkKhaki")
    DARK_KHAKI("DarkKhaki"),
    @XmlEnumValue("DarkMagenta")
    DARK_MAGENTA("DarkMagenta"),
    @XmlEnumValue("DarkOliveGreen")
    DARK_OLIVE_GREEN("DarkOliveGreen"),
    @XmlEnumValue("Darkorange")
    DARKORANGE("Darkorange"),
    @XmlEnumValue("DarkOrchid")
    DARK_ORCHID("DarkOrchid"),
    @XmlEnumValue("DarkRed")
    DARK_RED("DarkRed"),
    @XmlEnumValue("DarkSalmon")
    DARK_SALMON("DarkSalmon"),
    @XmlEnumValue("DarkSeaGreen")
    DARK_SEA_GREEN("DarkSeaGreen"),
    @XmlEnumValue("DarkSlateBlue")
    DARK_SLATE_BLUE("DarkSlateBlue"),
    @XmlEnumValue("DarkSlateGray")
    DARK_SLATE_GRAY("DarkSlateGray"),
    @XmlEnumValue("DarkSlateGrey")
    DARK_SLATE_GREY("DarkSlateGrey"),
    @XmlEnumValue("DarkTurquoise")
    DARK_TURQUOISE("DarkTurquoise"),
    @XmlEnumValue("DarkViolet")
    DARK_VIOLET("DarkViolet"),
    @XmlEnumValue("DeepPink")
    DEEP_PINK("DeepPink"),
    @XmlEnumValue("DeepSkyBlue")
    DEEP_SKY_BLUE("DeepSkyBlue"),
    @XmlEnumValue("DimGray")
    DIM_GRAY("DimGray"),
    @XmlEnumValue("DimGrey")
    DIM_GREY("DimGrey"),
    @XmlEnumValue("DodgerBlue")
    DODGER_BLUE("DodgerBlue"),
    @XmlEnumValue("FireBrick")
    FIRE_BRICK("FireBrick"),
    @XmlEnumValue("FloralWhite")
    FLORAL_WHITE("FloralWhite"),
    @XmlEnumValue("ForestGreen")
    FOREST_GREEN("ForestGreen"),
    @XmlEnumValue("Fuchsia")
    FUCHSIA("Fuchsia"),
    @XmlEnumValue("Gainsboro")
    GAINSBORO("Gainsboro"),
    @XmlEnumValue("GhostWhite")
    GHOST_WHITE("GhostWhite"),
    @XmlEnumValue("Gold")
    GOLD("Gold"),
    @XmlEnumValue("GoldenRod")
    GOLDEN_ROD("GoldenRod"),
    @XmlEnumValue("Gray")
    GRAY("Gray"),
    @XmlEnumValue("Grey")
    GREY("Grey"),
    @XmlEnumValue("Green")
    GREEN("Green"),
    @XmlEnumValue("GreenYellow")
    GREEN_YELLOW("GreenYellow"),
    @XmlEnumValue("HoneyDew")
    HONEY_DEW("HoneyDew"),
    @XmlEnumValue("HotPink")
    HOT_PINK("HotPink"),
    @XmlEnumValue("IndianRed")
    INDIAN_RED("IndianRed"),
    @XmlEnumValue("Indigo")
    INDIGO("Indigo"),
    @XmlEnumValue("Ivory")
    IVORY("Ivory"),
    @XmlEnumValue("Khaki")
    KHAKI("Khaki"),
    @XmlEnumValue("Lavender")
    LAVENDER("Lavender"),
    @XmlEnumValue("LavenderBlush")
    LAVENDER_BLUSH("LavenderBlush"),
    @XmlEnumValue("LawnGreen")
    LAWN_GREEN("LawnGreen"),
    @XmlEnumValue("LemonChiffon")
    LEMON_CHIFFON("LemonChiffon"),
    @XmlEnumValue("LightBlue")
    LIGHT_BLUE("LightBlue"),
    @XmlEnumValue("LightCoral")
    LIGHT_CORAL("LightCoral"),
    @XmlEnumValue("LightCyan")
    LIGHT_CYAN("LightCyan"),
    @XmlEnumValue("LightGoldenRodYellow")
    LIGHT_GOLDEN_ROD_YELLOW("LightGoldenRodYellow"),
    @XmlEnumValue("LightGray")
    LIGHT_GRAY("LightGray"),
    @XmlEnumValue("LightGrey")
    LIGHT_GREY("LightGrey"),
    @XmlEnumValue("LightGreen")
    LIGHT_GREEN("LightGreen"),
    @XmlEnumValue("LightPink")
    LIGHT_PINK("LightPink"),
    @XmlEnumValue("LightSalmon")
    LIGHT_SALMON("LightSalmon"),
    @XmlEnumValue("LightSeaGreen")
    LIGHT_SEA_GREEN("LightSeaGreen"),
    @XmlEnumValue("LightSkyBlue")
    LIGHT_SKY_BLUE("LightSkyBlue"),
    @XmlEnumValue("LightSlateGray")
    LIGHT_SLATE_GRAY("LightSlateGray"),
    @XmlEnumValue("LightSlateGrey")
    LIGHT_SLATE_GREY("LightSlateGrey"),
    @XmlEnumValue("LightSteelBlue")
    LIGHT_STEEL_BLUE("LightSteelBlue"),
    @XmlEnumValue("LightYellow")
    LIGHT_YELLOW("LightYellow"),
    @XmlEnumValue("Lime")
    LIME("Lime"),
    @XmlEnumValue("LimeGreen")
    LIME_GREEN("LimeGreen"),
    @XmlEnumValue("Linen")
    LINEN("Linen"),
    @XmlEnumValue("Magenta")
    MAGENTA("Magenta"),
    @XmlEnumValue("Maroon")
    MAROON("Maroon"),
    @XmlEnumValue("MediumAquaMarine")
    MEDIUM_AQUA_MARINE("MediumAquaMarine"),
    @XmlEnumValue("MediumBlue")
    MEDIUM_BLUE("MediumBlue"),
    @XmlEnumValue("MediumOrchid")
    MEDIUM_ORCHID("MediumOrchid"),
    @XmlEnumValue("MediumPurple")
    MEDIUM_PURPLE("MediumPurple"),
    @XmlEnumValue("MediumSeaGreen")
    MEDIUM_SEA_GREEN("MediumSeaGreen"),
    @XmlEnumValue("MediumSlateBlue")
    MEDIUM_SLATE_BLUE("MediumSlateBlue"),
    @XmlEnumValue("MediumSpringGreen")
    MEDIUM_SPRING_GREEN("MediumSpringGreen"),
    @XmlEnumValue("MediumTurquoise")
    MEDIUM_TURQUOISE("MediumTurquoise"),
    @XmlEnumValue("MediumVioletRed")
    MEDIUM_VIOLET_RED("MediumVioletRed"),
    @XmlEnumValue("MidnightBlue")
    MIDNIGHT_BLUE("MidnightBlue"),
    @XmlEnumValue("MintCream")
    MINT_CREAM("MintCream"),
    @XmlEnumValue("MistyRose")
    MISTY_ROSE("MistyRose"),
    @XmlEnumValue("Moccasin")
    MOCCASIN("Moccasin"),
    @XmlEnumValue("NavajoWhite")
    NAVAJO_WHITE("NavajoWhite"),
    @XmlEnumValue("Navy")
    NAVY("Navy"),
    @XmlEnumValue("OldLace")
    OLD_LACE("OldLace"),
    @XmlEnumValue("Olive")
    OLIVE("Olive"),
    @XmlEnumValue("OliveDrab")
    OLIVE_DRAB("OliveDrab"),
    @XmlEnumValue("Orange")
    ORANGE("Orange"),
    @XmlEnumValue("OrangeRed")
    ORANGE_RED("OrangeRed"),
    @XmlEnumValue("Orchid")
    ORCHID("Orchid"),
    @XmlEnumValue("PaleGoldenRod")
    PALE_GOLDEN_ROD("PaleGoldenRod"),
    @XmlEnumValue("PaleGreen")
    PALE_GREEN("PaleGreen"),
    @XmlEnumValue("PaleTurquoise")
    PALE_TURQUOISE("PaleTurquoise"),
    @XmlEnumValue("PaleVioletRed")
    PALE_VIOLET_RED("PaleVioletRed"),
    @XmlEnumValue("PapayaWhip")
    PAPAYA_WHIP("PapayaWhip"),
    @XmlEnumValue("PeachPuff")
    PEACH_PUFF("PeachPuff"),
    @XmlEnumValue("Peru")
    PERU("Peru"),
    @XmlEnumValue("Pink")
    PINK("Pink"),
    @XmlEnumValue("Plum")
    PLUM("Plum"),
    @XmlEnumValue("PowderBlue")
    POWDER_BLUE("PowderBlue"),
    @XmlEnumValue("Purple")
    PURPLE("Purple"),
    @XmlEnumValue("Red")
    RED("Red"),
    @XmlEnumValue("RosyBrown")
    ROSY_BROWN("RosyBrown"),
    @XmlEnumValue("RoyalBlue")
    ROYAL_BLUE("RoyalBlue"),
    @XmlEnumValue("SaddleBrown")
    SADDLE_BROWN("SaddleBrown"),
    @XmlEnumValue("Salmon")
    SALMON("Salmon"),
    @XmlEnumValue("SandyBrown")
    SANDY_BROWN("SandyBrown"),
    @XmlEnumValue("SeaGreen")
    SEA_GREEN("SeaGreen"),
    @XmlEnumValue("SeaShell")
    SEA_SHELL("SeaShell"),
    @XmlEnumValue("Sienna")
    SIENNA("Sienna"),
    @XmlEnumValue("Silver")
    SILVER("Silver"),
    @XmlEnumValue("SkyBlue")
    SKY_BLUE("SkyBlue"),
    @XmlEnumValue("SlateBlue")
    SLATE_BLUE("SlateBlue"),
    @XmlEnumValue("SlateGray")
    SLATE_GRAY("SlateGray"),
    @XmlEnumValue("SlateGrey")
    SLATE_GREY("SlateGrey"),
    @XmlEnumValue("Snow")
    SNOW("Snow"),
    @XmlEnumValue("SpringGreen")
    SPRING_GREEN("SpringGreen"),
    @XmlEnumValue("SteelBlue")
    STEEL_BLUE("SteelBlue"),
    @XmlEnumValue("Tan")
    TAN("Tan"),
    @XmlEnumValue("Teal")
    TEAL("Teal"),
    @XmlEnumValue("Thistle")
    THISTLE("Thistle"),
    @XmlEnumValue("Tomato")
    TOMATO("Tomato"),
    @XmlEnumValue("Turquoise")
    TURQUOISE("Turquoise"),
    @XmlEnumValue("Violet")
    VIOLET("Violet"),
    @XmlEnumValue("Wheat")
    WHEAT("Wheat"),
    @XmlEnumValue("White")
    WHITE("White"),
    @XmlEnumValue("WhiteSmoke")
    WHITE_SMOKE("WhiteSmoke"),
    @XmlEnumValue("Yellow")
    YELLOW("Yellow"),
    @XmlEnumValue("YellowGreen")
    YELLOW_GREEN("YellowGreen");
    private final String value;

    HtmlColorList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HtmlColorList fromValue(String v) {
        for (HtmlColorList c: HtmlColorList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
