//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.03 at 11:33:56 AM EEST 
//


package tr.com.agem.arya.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resizerdirAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="resizerdirAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="left"/>
 *     &lt;enumeration value="right"/>
 *     &lt;enumeration value="top"/>
 *     &lt;enumeration value="bottom"/>
 *     &lt;enumeration value="bottomend"/>
 *     &lt;enumeration value="bottomleft"/>
 *     &lt;enumeration value="bottomright"/>
 *     &lt;enumeration value="topleft"/>
 *     &lt;enumeration value="topright"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "resizerdirAttributeType")
@XmlEnum
public enum ResizerdirAttributeType {


    /**
     * left: Resized to the left.
     * 
     */
    @XmlEnumValue("left")
    LEFT("left"),

    /**
     * right: Resized to the right.
     * 
     */
    @XmlEnumValue("right")
    RIGHT("right"),

    /**
     * top: Resized up.
     * 
     */
    @XmlEnumValue("top")
    TOP("top"),

    /**
     * bottom: Resized down.
     * 
     */
    @XmlEnumValue("bottom")
    BOTTOM("bottom"),

    /**
     * bottomend: (Requires Gecko 1.9.2) Resized down and toward the end of the line (toward the right for left-to-right locales, toward the left for right-to-left locales).
     * 
     */
    @XmlEnumValue("bottomend")
    BOTTOMEND("bottomend"),

    /**
     * bottomleft: Resized down and to the left.
     * 
     */
    @XmlEnumValue("bottomleft")
    BOTTOMLEFT("bottomleft"),

    /**
     * bottomright: Resized down and to the right.
     * 
     */
    @XmlEnumValue("bottomright")
    BOTTOMRIGHT("bottomright"),

    /**
     * topleft: Resized up and to the left.
     * 
     */
    @XmlEnumValue("topleft")
    TOPLEFT("topleft"),

    /**
     * topright: Resized up and to the right.
     * 
     */
    @XmlEnumValue("topright")
    TOPRIGHT("topright");
    private final String value;

    ResizerdirAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResizerdirAttributeType fromValue(String v) {
        for (ResizerdirAttributeType c: ResizerdirAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
