//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.03 at 11:04:58 AM EEST 
//


package tr.com.agem.arya.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sizetopopupAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sizetopopupAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="always"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "sizetopopupAttributeType")
@XmlEnum
public enum SizetopopupAttributeType {


    /**
     * 
     *             none: The width of the popup will not be constrained to the size of the menu.
     *           
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * 
     *             always: If set to always, the menu's width will be the same as that necessary for the menupopup. If the menu has a maximum width, the popup will also be this width.
     *           
     * 
     */
    @XmlEnumValue("always")
    ALWAYS("always");
    private final String value;

    SizetopopupAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SizetopopupAttributeType fromValue(String v) {
        for (SizetopopupAttributeType c: SizetopopupAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
