//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.03 at 04:40:57 PM EEST 
//


package tr.com.agem.arya.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for substateAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="substateAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="before"/>
 *     &lt;enumeration value="after"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "substateAttributeType")
@XmlEnum
public enum SubstateAttributeType {


    /**
     * 
     *             before: The element immediately before the splitter is collapsed.
     *           
     * 
     */
    @XmlEnumValue("before")
    BEFORE("before"),

    /**
     * 
     *             after: The element immediately after the splitter is collapsed.
     *           
     * 
     */
    @XmlEnumValue("after")
    AFTER("after");
    private final String value;

    SubstateAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubstateAttributeType fromValue(String v) {
        for (SubstateAttributeType c: SubstateAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
