//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 05:11:41 PM EEST 
//


package tr.com.agem.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for buttontypeAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="buttontypeAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="checkbox"/>
 *     &lt;enumeration value="menutypemenu"/>
 *     &lt;enumeration value="menu-buttonmenu-buttonmenu"/>
 *     &lt;enumeration value="radio"/>
 *     &lt;enumeration value="repeat"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "buttontypeAttributeType")
@XmlEnum
public enum ButtontypeAttributeType {


    /**
     * checkbox: This type of button can be in two states. The user can click the button to switch between the states. This is not the same as a checkbox because it looks like a button.
     * 
     */
    @XmlEnumValue("checkbox")
    CHECKBOX("checkbox"),

    /**
     * menu: Set the type attribute to the value menu to create a button with a menu popup. Place a menupopup element inside the button in this case. The user may click anywhere on the button to open and close the menu.
     * 
     */
    @XmlEnumValue("menutypemenu")
    MENUTYPEMENU("menutypemenu"),

    /**
     * menu-button: You can also use the value menu-button to create a button with a menu. Unlike the menu type, this type requires the user to press the arrow to open the menu, but a different command may be invoked when the main part of the button is pressed.
     * 
     */
    @XmlEnumValue("menu-buttonmenu-buttonmenu")
    MENU_BUTTONMENU_BUTTONMENU("menu-buttonmenu-buttonmenu"),

    /**
     * radio: The button acts like a radio button. Only one button in the group can be on a once.
     * 
     */
    @XmlEnumValue("radio")
    RADIO("radio"),

    /**
     * repeat: (New in Firefox 3) This button will fire its command event repeatedly while the mouse button is held down.
     * 
     */
    @XmlEnumValue("repeat")
    REPEAT("repeat");
    private final String value;

    ButtontypeAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ButtontypeAttributeType fromValue(String v) {
        for (ButtontypeAttributeType c: ButtontypeAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
