//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 05:11:41 PM EEST 
//


package tr.com.agem.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for equalsizeAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="equalsizeAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="always"/>
 *     &lt;enumeration value="never"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "equalsizeAttributeType")
@XmlEnum
public enum EqualsizeAttributeType {


    /**
     * For a horizontally oriented element, this will make all of its children have the width of the widest child. For a vertically oriented element, this will make its children all have the height of the tallest child.
     * 
     */
    @XmlEnumValue("always")
    ALWAYS("always"),

    /**
     * All of the children are displayed at the size required by the content or as specified by the width and height attributes or the CSS width and height properties. 
     * 
     */
    @XmlEnumValue("never")
    NEVER("never");
    private final String value;

    EqualsizeAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EqualsizeAttributeType fromValue(String v) {
        for (EqualsizeAttributeType c: EqualsizeAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
