//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 05:11:41 PM EEST 
//


package tr.com.agem.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for panelfadeAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="panelfadeAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="slow"/>
 *     &lt;enumeration value="fast"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "panelfadeAttributeType")
@XmlEnum
public enum PanelfadeAttributeType {


    /**
     * none: The panels doesn't automatically fade away.
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * slow: The panels slowly fades away after a short time.
     * 
     */
    @XmlEnumValue("slow")
    SLOW("slow"),

    /**
     * fast: The panels quickly fades away after a short time.
     * 
     */
    @XmlEnumValue("fast")
    FAST("fast");
    private final String value;

    PanelfadeAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PanelfadeAttributeType fromValue(String v) {
        for (PanelfadeAttributeType c: PanelfadeAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
