//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 05:11:41 PM EEST 
//


package tr.com.agem.metadata.xul.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for textboxtypeAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="textboxtypeAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="autocomplete"/>
 *     &lt;enumeration value="number"/>
 *     &lt;enumeration value="password"/>
 *     &lt;enumeration value="search"/>
 *     &lt;enumeration value="timed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "textboxtypeAttributeType")
@XmlEnum
public enum TextboxtypeAttributeType {


    /**
     * autocomplete: A textbox that supports autocomplete. For more information about autocomplete textboxes, see the autocomplete documentation (XPFE [Thunderbird/SeaMonkey]) (Firefox)
     * 
     */
    @XmlEnumValue("autocomplete")
    AUTOCOMPLETE("autocomplete"),

    /**
     * number: (Requires Gecko 1.9) A textbox that only allows the user to enter numbers. In addition, arrow buttons appear next to the textbox to let the user step through values. There are several attributes that allow the number textbox to be configured, including decimalplaces, min, max, increment, wraparound, hidespinbuttons, and textbox.value.
     * 
     */
    @XmlEnumValue("number")
    NUMBER("number"),

    /**
     * password: A textbox that hides what is typed, used for entering passwords.
     * 
     */
    @XmlEnumValue("password")
    PASSWORD("password"),

    /**
     * search: (Requires Gecko 1.9.1) A textbox intended for searching. The command event will fire as the user modifies the value. A listener for the command event should update search results. If the searchbutton attribute is set to true, the command event is only fired if the user presses the search button or presses the Enter key. You may specify grey text to appear when the search box is empty using the emptytext attribute, and a timeout may be set for the command event using the timeout attribute (defaults to 500).
     * 
     */
    @XmlEnumValue("search")
    SEARCH("search"),

    /**
     * timed: (Deprecated) This textbox will fire a command event after the user types characters and a certain time has passed. The delay is set with the timeout attribute. The command event will fire if the user presses the Enter key. The timed type is deprecated in Gecko 1.9.1 and the search textbox may be used instead.
     * 
     */
    @XmlEnumValue("timed")
    TIMED("timed");
    private final String value;

    TextboxtypeAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TextboxtypeAttributeType fromValue(String v) {
        for (TextboxtypeAttributeType c: TextboxtypeAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
